<form name = "datamhsform" method="post">
<fieldset><legend> <?php echo "Data Entry Referensi"?></legend>

<div class="topnav">
  <a href="/pelajaran/pelajaran/view">Matakuliah</a>
  <a href="/siswa/siswa/view">Mahasiswa</a>
  <a href="#dosen">Dosen</a>
  <a href="#ruangan">Ruangan</a>
  <a href="/akademik/akademik/view">Tahun Akademik</a>
  <a href="/pengisian/pengisian/view">Batas Pengisian Krs</a>
  <a href="/penjadwalan/penjadwalan/view">Penjadwalan Aktivasi</a>
</div>
<style>
/* Add a black background color to the top navigation */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}

.topnav a:hover {
  border-bottom: 3px solid red;
}

.topnav a.active {
  border-bottom: 3px solid red;
}
</style>
<br><br>


