<script type="text/javascript">
    dojo.addOnLoad(function(){
<?php if (!$this->larrresult) { ?>                    
                    dijit.byId('field8').set('value','');
                    dijit.byId('field8').set('placeHolder','Select');                    
                    dijit.byId('field10').set('value','');
                    dijit.byId('field10').set('placeHolder','Select');
                    dijit.byId('field5').set('value','');
                    dijit.byId('field5').set('placeHolder','Select');
<?php } ?>
            });
</script>
<fieldset>
	<legend>
		<?php echo $this->translate("Exam Scaling Setup"); ?>
	</legend>
	<form
		action="<?php echo $this->baseUrl(); ?>/examination/examscalingsetup/index/search/1"
		method="POST">
		<table width="100%">
			<tr>
				<td><?php echo $this->translate("Semester"); ?></td>
				<td><?php echo $this->lobjform->field8; ?></td>
				<td><?php echo $this->translate("Scheme"); ?></td>
				<td><?php echo $this->lobjform->field10; ?></td>
			</tr>
			<tr>
				<td><?php echo $this->translate("Program"); ?></td>
				<td><?php echo $this->lobjform->field5; ?></td>
			</tr>
			<tr>
				<td colspan="6" style="height: 10px"></td>
			</tr>
			<tr>
				<td align="center" colspan="6"><?php echo $this->lobjform->Search; ?>
					<input type="button" class="NormalBtn" dojotype="dijit.form.Button"
					label="<?php echo $this->translate("Add"); ?>"
					onclick="window.location.href='<?php echo $this->url(array('module' => 'examination', 'controller' => 'examscalingsetup', 'action' => 'addexamscalingsetup'), 'default', true); ?>';" />
					<?php echo $this->lobjform->Clear; ?>
				</td>
			</tr>
		</table>
	</form>
</fieldset>
</br>
<fieldset>
	<table class="table" width="100%" cellpadding="5" cellspacing="1">
		<tr>
			<th><?php echo $this->translate('Semester'); ?></th>
			<th><?php echo $this->translate("Scheme"); ?></th>
			<th><?php echo $this->translate("Faculty"); ?></th>
		</tr>
		<?php if (count($this->paginator)): ?>
		<?php foreach ($this->paginator as $list): ?>
		<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0", "#FFFFFF"))->next() ?>">
			<td><a
				href="<?php echo $this->url(array('module' => 'examination', 'controller' => 'examscalingsetup', 'action' => 'editexamscalingsetup', 'id' => $list['IdExamScaling']), 'default', true); ?>"><?php echo (isset($list['semestercode'])) ? $list['semestercode']  : '' ; ?>
			</a></td>
			<td><?php echo (isset($list['EnglishDescription'])) ? $list['EnglishDescription']  : '' ; ?>
			</td>
			<td><?php echo (isset($list['CollegeName'])) ? $list['CollegeName']  : '' ; ?>
			</td>
			<?php endforeach; ?>
			<?php endif; ?>
		
		
		<tr>
			<td colspan="8" align="right"><div class="pagination">
					<?php echo $this->paginationControl($this->lobjpaginator, 'Sliding',
							'/partials/my_pagination_control.phtml'); ?>
				</div></td>
		</tr>


	</table>
</fieldset>
