<form name = "datamhsform" method="post">

<style>
.nihaya {
  background-color: #C4B65C;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
}
</style>

<style>
/* Add a black background color to the top navigation */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}

.topnav a:hover {
  border-bottom: 3px solid red;
}

.topnav a.active {
  border-bottom: 3px solid red;
}
</style>
<br><br>

<div class="topnav">
  <a href="/pelajaran/pelajaran/view">Matakuliah</a>
  <a href="siswa/siswa/view">Mahasiswa</a>
  <a href="/dosen/dosen/view">Dosen</a>
  <a href="ruangan/ruangan/view">Ruangan</a>
  <a href="/akademik/akademik/view">Tahun Akademik</a>
  <a href="/pengisian/pengisian/view">Batas Pengisian Krs</a>
  <a href="/penjadwalan/penjadwalan/view">Penjadwalan Aktivasi</a>
</div>

<br><br><div class="nihaya">
<fieldset><legend> <?php echo "Data Entry Referensi"?></legend>

<style>
/* Add a black background color to the top navigation */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}

.topnav a:hover {
  border-bottom: 3px solid red;
}

.topnav a.active {
  border-bottom: 3px solid red;
}
</style>
<br><br>

<input type = "hidden" id= "id" name="id" value="<?php echo $this->datapersonal['id']?>">
<table>
<tr><th>Ruangan</th>
<td><input type="text" name="ruangan" id= "ruangan" value="<?php echo $this->datapersonal['ruangan']?>">
<tr><th>Kapasitas</th>
<td><input type="text" name="kapasitas" id= "kapasitas"value="<?php echo $this->datapersonal['kapasitas']?>">
<tr><th>Kode Mk</th>
<td><input type="text" name = "kodemk" id="kodemk" value="<?php echo $this->datapersonal['kodemk']?>" >
<tr><th>Jam Matakuliah</th>
<td><input type="time" name = "jammatakuliah" id="jammatakuliah" value="<?php echo $this->datapersonal['jammatakuliah']?>" >


<br><br>
<tr><td colspan="2">
<input type="submit" name = "save" value="save">
<input type="submit" name = "delete" value="delete">
<input type="submit" name = "update" value="update">
<input type="submit" name = "search" value="search">
</td></tr>
</table>
</form>
</div>
</fieldset>

<br><br><div class="nihaya">
<fieldset><legend><table class="table" border="1"><h1> Data Ruangank</h1><tr><th>Ruangan</th><th>Kapasitas</th><th>Kode Mk</th><th>Jam Matakuliah</th></legend><?php foreach($this->refmhs as $mhs) {?> 
<tr><td><?php echo $mhs['ruangan'];?></td></th> 
<td><?php echo $mhs['kapasitas'];?></td> 
<td><?php echo $mhs['kodemk'];?></td>
<td><?php echo $mhs['jammatakuliah'];?></td>
<?php }?>

  </table>