<form name = "datamhsform" method="post">

<style>
body {
 background-image: url('/images/images/index/vector2.jpg');
}
.ade {
  background-color: #ffffff;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
}
.topnav {
  overflow: hidden;
  background-color: #7A7346;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #AB9F5A;
  color: black;
}

.topnav a.active {
  background-color: #C8B858;
  color: white;
}

.topnav-right {
  float: right;
}

input[type="submit"] {
  background-color: #575445;
  color: black;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
 width: 90px; 
    padding: 20px; 
    cursor: 
    pointer; 
    box-shadow: 6px 6px 5px; #999; 
    -webkit-box-shadow: 6px 6px 5px #575445; 
    -moz-box-shadow: 6px 6px 5px #999; 
    font-weight: bold; 
    background: #B4A768; 
    color: #000; 
    border-radius: 10px; 
    border: 1px solid #999; 
    font-size: 100%;
}
</style>
</head>
<body>

<!DOCTYPE html>
<html>
<head>
<style>
html, body {
  height: 100%;
}



img.two {
  height: 40%;
  width: 100%;
}

}
</style>
</head>
</html>

<div class="topnav">
  <a  href="/homepage/homepage/view">Home</a>
  <a href="/referensi/referensi/view" class="active">Referensi</a>
  <a href="/kurikulum/kurikulum/view">Kurikulum</a>
  <a href="/penjadwalan/penjadwalan">Penjadwalan</a>
  <a href="/krs/krs/view">KRS</a>
  <a href="/data-personal/mahasiswa/view>Transcript"></a>
  
  <div class="topnav-right">
    <a href="/index">Logout</a>
    
  </div>
</div>
</style>

<style>
.sisi {
  background-color: #C4B65C;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
}
</style>

<style>
/* Add a black background color to the top navigation */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}

.topnav a:hover {
  border-bottom: 3px solid red;
}

.topnav a.active {
  border-bottom: 3px solid red;
}
</style>
<br><br>

<div class="topnav">
  <a href="/pelajaran/pelajaran/view">Matakuliah</a>
  <a href="siswa/siswa/view">Mahasiswa</a>
  <a href="/dosen/dosen/view">Dosen</a>
  <a href="ruangan/ruangan/view">Ruangan</a>
  <a href="/akademik/akademik/view">Tahun Akademik</a>
  <a href="/pengisian/pengisian/view">Batas Pengisian Krs</a>
  <a href="/penjadwalan/penjadwalan/view">Penjadwalan Aktivasi</a>
</div>

<br><br><div class="sisi">
<fieldset><legend> <?php echo "Data Entry Referensi"?></legend>

<style>
/* Add a black background color to the top navigation */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}

.topnav a:hover {
  border-bottom: 3px solid red;
}

.topnav a.active {
  border-bottom: 3px solid red;
}
</style>
<br><br>

<input type = "hidden" id= "id" name="id" value="<?php echo $this->datapersonal['id']?>">
<table>
<tr><th>Ruangan</th>
<td><input type="text" name="ruangan" id= "ruangan" value="<?php echo $this->datapersonal['ruangan']?>">
<tr><th>Kapasitas</th>
<td><input type="text" name="kapasitas" id= "kapasitas"value="<?php echo $this->datapersonal['kapasitas']?>">
<tr><th>Kode Mk</th>
<td><input type="text" name = "kodemk" id="kodemk" value="<?php echo $this->datapersonal['kodemk']?>" >
<tr><th>Jam Matakuliah</th>
<td><input type="time" name = "jammatakuliah" id="jammatakuliah" value="<?php echo $this->datapersonal['jammatakuliah']?>" >


<br><br>
<tr><td colspan="2">
<input type="submit" name = "save" value="save">
<input type="submit" name = "delete" value="delete">
<input type="submit" name = "update" value="update">
<input type="submit" name = "search" value="search">
</td></tr>
</table>
</form>
</div>
</fieldset>

<br><br><div class="sisi">
<fieldset><legend><table class="table" border="1"><h1> Data Ruangank</h1><tr><th>Ruangan</th><th>Kapasitas</th><th>Kode Mk</th><th>Jam Matakuliah</th></legend><?php foreach($this->refmhs as $mhs) {?> 
<tr><td><?php echo $mhs['ruangan'];?></td></th> 
<td><?php echo $mhs['kapasitas'];?></td> 
<td><?php echo $mhs['kodemk'];?></td>
<td><?php echo $mhs['jammatakuliah'];?></td>
<?php }?>

  </table>

