<script type="text/javascript">
    dojo.addOnLoad(function(){
        //$('#totalmarks').attr("readonly","readonly");
        <?php if(isset($_POST) && (!empty($_POST))){ ?>                
                fnGetSchmeList("<?php echo $_POST['IdFaculty'];?>");                               
                setTimeout(function() {
                       dijit.byId('IdScheme').setValue("<?php echo $_POST['IdScheme'];?>");
                       setTimeout(function() {
                            dijit.byId('IdProgram').setValue('<?php echo $_POST['IdProgram'];?>');
                            setTimeout(function() {
                                dijit.byId('IdCourse').setValue('<?php echo $_POST['IdCourse'];?>');
                            }, 1250);
                        }, 1250);
                }, 1250);
                <?php if($_POST['semestercode'] == ''){?>
                    dijit.byId('semestercode').set('value','');
                    dijit.byId('semestercode').set('placeHolder','Select');
                <?php }else{ ?>
                    dijit.byId('semestercode').setValue('<?php echo $_POST['semestercode'];?>');
                <?php } ?>
        <?php }else{ ?>
        dijit.byId('IdFaculty').set('value','');
        dijit.byId('IdFaculty').set('placeHolder','Select');
        dijit.byId('IdScheme').set('value','');
        dijit.byId('IdScheme').set('placeHolder','Select');
        dijit.byId('IdCourse').set('value','');
        dijit.byId('IdCourse').set('placeHolder','Select');
        dijit.byId('IdProgram').set('value','');
        dijit.byId('IdProgram').set('placeHolder','Select');
        dijit.byId('semestercode').set('value','');
        dijit.byId('semestercode').set('placeHolder','Select');        
        <?php } ?>
        dijit.byId('FromProgram').set('value','');
        dijit.byId('FromProgram').set('placeHolder','Select');
        dijit.byId('ToProgram').set('value','');
        dijit.byId('ToProgram').set('placeHolder','Select');
        dijit.byId('FromCourse').set('value','');
        dijit.byId('FromCourse').set('placeHolder','Select');
        dijit.byId('ToCourse').set('value','');
        dijit.byId('ToCourse').set('placeHolder','Select');
        dijit.byId('FromSemester').set('value','');
        dijit.byId('FromSemester').set('placeHolder','Select');
        dijit.byId('ToSemester').set('value','');
        dijit.byId('ToSemester').set('placeHolder','Select');
        var markLen = $('.mark').length;
        if(markLen > 0){
            for(var i=0;i<markLen;i++){
                $('#marks_'+i).attr("readonly","readonly");
            }
        }
    });
    
    function fnGetSchmeList(IdFaculty){ 
        if(IdFaculty != "") {
            var xhrArgs = {
                url: "<?php echo $this->baseUrl(); ?>"+"/examination/marksdistributionmaster/getschemelist/IdFaculty/"+IdFaculty,
                handleAs:'json',
                load:function(data){                    
                    AutoFillNextEditableDropDown("IdScheme",data);
                }
            }
            dojo.xhrGet(xhrArgs);
        }
    }

    function fnGetProgramList(IdScheme){
        var IdFaculty = dijit.byId("IdFaculty").value;
        var IdScheme = dijit.byId("IdScheme").value;

        var flag = true;

        if(IdFaculty == '0'){
            if(IdScheme != '0'){
                alert('Scheme should be all if Faculty is all');
                flag = false;
                //dijit.byId('IdFaculty').set('value','');
                //dijit.byId('IdFaculty').set('placeHolder','Select');
                dijit.byId('IdScheme').set('value','');
                dijit.byId('IdScheme').set('placeHolder','Select');
            }
        }

        if(IdScheme == '0'){
            if(IdFaculty != '0'){
                alert('Faculty should be all if Scheme is all');
                flag = false;
                dijit.byId('IdFaculty').set('value','');
                dijit.byId('IdFaculty').set('placeHolder','Select');
                //dijit.byId('IdScheme').set('value','');
                //dijit.byId('IdScheme').set('placeHolder','Select');
            }
        }

        if(flag){
            if(IdScheme != "" && IdFaculty !='') {
                var xhrArgs = {
                    url: "<?php echo $this->baseUrl(); ?>"+"/examination/marksdistributionmaster/getprogramlist/IdFaculty/"+IdFaculty+"/IdScheme/"+IdScheme,
                    handleAs:'json',
                    load:function(data){
                        AutoFillNextEditableDropDown("IdProgram",data);
                    }
                }
                dojo.xhrGet(xhrArgs);
            }
        }
    }



    function fnGetCourseList(IdProgram){
        if(IdProgram != "") {
            var xhrArgs = {
                url: "<?php echo $this->baseUrl(); ?>"+"/examination/marksdistributionmaster/getcourselist/IdProgram/"+IdProgram,
                handleAs:'json',
                load:function(data){						
                    AutoFillNextEditableDropDown("IdCourse",data);
                }
            }
            dojo.xhrGet(xhrArgs);
        }
    }

    function fnGettoCourseList(IdProgram){
        if(IdProgram != "") {
            var xhrArgs = {
                url: "<?php echo $this->baseUrl(); ?>"+"/examination/marksdistributionmaster/getcourselist/IdProgram/"+IdProgram,
                handleAs:'json',
                load:function(data){
                    AutoFillNextEditableDropDown("ToCourse",data);
                }
            }
            dojo.xhrGet(xhrArgs);
        }
    }

    function fnGetFromCourseList(IdProgram){
        if(IdProgram != "") {
            var xhrArgs = {
                url: "<?php echo $this->baseUrl(); ?>"+"/examination/marksdistributionmaster/getfromcourselist/IdProgram/"+IdProgram,
                handleAs:'json',
                load:function(data){
                    AutoFillNextEditableDropDown("FromCourse",data);
                }
            }
            dojo.xhrGet(xhrArgs);
        }
    }




    function AutoFillNextEditableDropDown(EditableDropDownId,JSONText){
        dijit.byId(EditableDropDownId).setValue("");
        var ddwidget = dijit.byId(EditableDropDownId);
        ddwidget.setAttribute('disabled', false);
        var options = {
            label:"name",
            identifier:"key",
            items:JSONText
        };
        ddwidget.store = new dojo.data.ItemFileReadStore( { data: options } );
    }

    function getComponent(){
        var IdCourse = dijit.byId("IdCourse").value;
        var semestercode = dijit.byId("semestercode").value
        if(IdCourse == '' || semestercode==''){
            alert('Please select Course and Semester');
            return false;
        }
        
        
        
        
    }

    function validateform(){
        var flag = true;
        var totalmarks = $('#totalmarks').val();
        if(totalmarks == ''){
            alert('Please insert total marks');
            return false;
        }
        var markLen = $('.mark').length;
        var markcount = 0;
        for(var i=0;i<markLen;i++){
            if($('#marks_'+i).val() != ''){
                markcount = parseFloat(markcount) + parseFloat($('#marks_'+i).val());
            }
        }       
        if(markcount != totalmarks){
            alert('count of components marks should be same as totalmarks');
            return false;
        }

        var percentlen = $('.percntage').length;
        var percentcount = 0;
        for(var i=0;i<markLen;i++){
            percentcount = parseFloat(percentcount) + parseFloat($('#percentage_'+i).val());
        }

        if(percentcount != parseFloat('100')){
            alert('count of percentage could not greater or less than to 100');
            return false;
        }
        return flag;
    }

    function insertmarksinrow(percentageId){
        var totalmarks = $('#totalmarks').val();
        if(totalmarks == ''){
            alert('First Insert marks');
            return false;
        }        
        var percentageval = $('#'+percentageId).val();
        if((isNaN(percentageval))){
            alert('Please insert numeric value in percentage');
            return false;
        }
        var ret = percentageId.split('_');
        var perkey = ret[1];
        var mark = ((totalmarks*percentageval)/100)
        $('#marks_'+perkey).val(mark);
    }


    function validateCopyForm(){
        var flag = true;
        var FromProgram = dijit.byId("FromProgram").value;
        var ToProgram = dijit.byId("ToProgram").value;
        var FromCourse = dijit.byId("FromCourse").value;
        var ToCourse = dijit.byId("ToCourse").value;
        var ToSemester = dijit.byId("ToSemester").value;
        var FromSemester = dijit.byId("FromSemester").value;
        if(FromProgram == ''){
            dijit.byId("FromProgram").attr('required','true');
            dijit.byId("FromProgram").focus();
            flag = false;
        }
        if(ToProgram == ''){
            dijit.byId("ToProgram").attr('required','true');
            dijit.byId("ToProgram").focus();
            flag = false;
        }
        if(FromCourse == ''){
            dijit.byId("FromCourse").attr('required','true');
            dijit.byId("FromCourse").focus();
            flag = false;
        }
        if(ToCourse == ''){
            dijit.byId("ToCourse").attr('required','true');
            dijit.byId("ToCourse").focus();
            flag = false;
        }
        if(FromSemester == ''){
            dijit.byId("FromSemester").attr('required','true');
            dijit.byId("FromSemester").focus();
            flag = false;
        }
        if(ToSemester == ''){
            dijit.byId("ToSemester").attr('required','true');
            dijit.byId("ToSemester").focus();
            flag = false;
        }
        return flag;
        
    }


    function inserttotalmarks(id){
        var totalmarks = 0;        
        var rowmarks = $('#'+id).val();        
        if((isNaN(rowmarks))){
            alert('Please insert numeric value in marks');
            return false;
        }
        if(rowmarks <= 0){
            alert('Marks should be greater than zero');
            return false;
        }

        var len = $('.mark').length;
        for(var i=0;i<len;i++){            
            rowmarks = $('#marks_'+i).val();
            if(rowmarks!=''){
                totalmarks = parseInt(totalmarks) + parseInt(rowmarks);
            }   
        }
        $('#totalmarks').val(parseInt(totalmarks));
    }
    
</script>
<Form dojoType="dijit.form.Form" id="myForm" action="" method="post"
	name="myForm">
	<fieldset>
		<legend>
			<?php echo $this->translate("Marks Distribution Master"); ?>
		</legend>
		<!--        <script type="dojo/method" event="onSubmit">
                if (this.validate()) {
                    var flag = validateform();
                    if(flag){
                        return true;
                    }else{
                        return false;
                    }
                } else {
                return false;
                }
            </script>-->
		<table class="table" width="100%">
			<tr>
				<th colspan="4"><?php echo $this->translate("Marks Distribution Master"); ?>
				</th>
			</tr>
			<?php if ($this->msgscheme == '1') {
				?>
			<tr>
				<td align="center" colspan="4" style="color: red;"><?php echo $this->translate('Component is already exist for this course'); ?>
				</td>
			</tr>
			<?php } ?>
			<tr>
				<td><?php echo $this->translate("Faculty"); ?></td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->IdFaculty; ?>
				</td>
				<td><?php echo $this->translate("Scheme"); ?></td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->IdScheme; ?>
					<?php echo $this->lobjMarksdistributionmasterForm->IdMarksDistributionMaster; ?>
					<?php echo $this->lobjMarksdistributionmasterForm->UpdDate; ?> <?php echo $this->lobjMarksdistributionmasterForm->UpdUser; ?>
				</td>
			</tr>
			<tr>
				<td><?php echo $this->translate($this->Program); ?></td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->IdProgram; ?>
				</td>
				<td><?php echo $this->translate($this->Subject); ?></td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->IdCourse; ?>
				</td>
			</tr>
			<tr>
				<td><?php echo $this->translate("Semester"); ?></td>
				<td colspan="3"><?php echo $this->lobjMarksdistributionmasterForm->semestercode; ?>
				</td>
			</tr>
			<?php if($this->errMsgMDMEntry=='1') { ?>
			<tr>
				<td align="center" colspan="4" style="color: red;">Sorry, you cannot
					add Marks Distribution for the selected combination as you have
					already one Marks Distribution.</td>
			</tr>
			<?php } ?>
			<tr>
				<td align="right" colspan="4"><input type='submit' name="Search"
					id="Search" class="NormalBtn" dojotype="dijit.form.Button"
					label="<?php echo $this->translate('Search') ?>" value='click'
					onclick="return getComponent()" /></td>
			</tr>
		</table>
		<div id="componentmaster">
			<table class="table" width="100%">
				<tr>
					<th><?php echo $this->translate("Component Type"); ?>
					</th>
					<th><?php echo $this->translate("Component Item"); ?>
					</th>
					<th><?php echo $this->translate("Marks"); ?></th>
					<th><?php echo $this->translate("Percentage"); ?></th>
				</tr>
				<?php if (isset($this->componentList) && (!empty($this->componentList))) {
					?>
				<?php $i = 0;
                        foreach ($this->componentList as $list) { ?>
				<tr>
					<td><?php echo ($list['comptype']) ? $list['comptype'] : '' ?></td>
					<td><input type="hidden" name="<?php echo 'componentitem_' . $i ?>"
						id="<?php echo 'componentitem_' . $i ?>"
						value="<?php echo $list['IdcomponentItem']; ?>"> <?php echo ($list['compitem']) ? $list['compitem'] : '' ?>
					</td>
					<td><input type="hidden" name="<?php echo 'componenttype_' . $i ?>"
						id="<?php echo 'componenttype_' . $i ?>"
						value="<?php echo $list['Idcomponents']; ?>"><input class="mark"
						type="text" onkeyup="inserttotalmarks(this.id)"
						dojoType="dijit.form.ValidationTextBox"
						name="<?php echo 'marks_' . $i; ?>"
						id="<?php echo 'marks_' . $i; ?>"></td>
					<!--<td><input type="hidden" name="<?php echo 'componenttype_' . $i ?>" id="<?php echo 'componenttype_' . $i ?>" value="<?php echo $list['Idcomponents']; ?>"><input class="mark" type="text" dojoType ="dijit.form.ValidationTextBox" name="<?php echo 'marks_' . $i; ?>" id="<?php echo 'marks_' . $i; ?>"></td>-->
					<td><input type="text" dojoType="dijit.form.ValidationTextBox"
						onkeyup="insertmarksinrow(this.id)"
						name="<?php echo 'percentage_' . $i; ?>"
						id="<?php echo 'percentage_' . $i; ?>"></td>
				</tr>
				<?php $i++;
                        } ?>
				<tr>
					<td></td>
					<td align="right">
						<!--<span style="color:RED"><?php //echo "(Please enter Total Marks first)"; ?></span>-->
						<span><b>Total Marks</b> </span><input type="hidden" name="count"
						id="count" value="<?php echo $i ?>"><input type="hidden"
						name="course" id="course"
						value="<?php echo ($this->componentList[0]['IdSubject']) ? $this->componentList[0]['IdSubject'] : '' ?>">
						<?php echo $this->translate('Total'); ?>
					
					</td>
					<td><input class="percntage" type="hidden" name="scheme"
						id="scheme"
						value="<?php echo (isset($this->scheme)) ? $this->scheme : '' ?>"><input
						type="hidden" name="faculty" id="faculty"
						value="<?php echo (isset($this->faculty)) ? $this->faculty : '' ?>"><input
						type="hidden" name="program" id="program"
						value="<?php echo (isset($this->program)) ? $this->program : '' ?>"><input
						type="hidden" name="semester" id="semester"
						value="<?php echo (isset($this->semester)) ? $this->semester : '' ?>"><input
						type="text" dojoType="dijit.form.ValidationTextBox"
						name="<?php echo 'totalmarks'; ?>"
						id="<?php echo 'totalmarks'; ?>"></td>
					<td>100%</td>
				</tr>
				<?php } ?>
			</table>
		</div>
		<table class="table" width="100%">

			<tr>
				<td align="right" colspan="4"><?php echo $this->lobjMarksdistributionmasterForm->Save; ?>
					<input type='button' class="NormalBtn" dojotype="dijit.form.Button"
					label="<?php echo $this->translate('Back') ?>" value='click'
					onclick="window.location.href='<?php echo $this->url(array('module' => 'examination', 'controller' => 'marksdistributionmaster', 'action' => 'index'), 'default', true); ?>';" />
				</td>
			</tr>
		</table>
	</fieldset>
	<br>
	<fieldset>
		<legend>
			<?php echo $this->translate("Marks Distribution Copy"); ?>
		</legend>
		<table class="table" width="100%">
			<?php if ($this->msgcopy == '1') {
				?>
			<tr>
				<td align="center" colspan="4" style="color: red;"><?php echo $this->translate('faculty and scheme should matched'); ?>
				</td>
			</tr>
			<?php } ?>
			<?php if ($this->msgcopycomponentnotexist == '1') {
				?>
			<tr>
				<td align="center" colspan="4" style="color: red;"><?php echo $this->translate('Component is not exist in given course, so setup is not possible'); ?>
				</td>
			</tr>
			<?php } ?>

			<?php if ($this->msgcopycomponentnotmatch == '1') {
				?>
			<tr>
				<td align="center" colspan="4" style="color: red;"><?php echo $this->translate('Component is not same in copying course and copy to course'); ?>
				</td>
			</tr>
			<?php } ?>

			<tr>
				<td><?php echo $this->translate('From Program')?>
				</td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->FromProgram;?>
				</td>
				<td><?php echo $this->translate('To Program')?>
				</td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->ToProgram;?>
				</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('From Course')?>
				</td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->FromCourse;?>
				</td>
				<td><?php echo $this->translate('To Course')?>
				</td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->ToCourse;?></td>
			</tr>
			<tr>
				<td><?php echo $this->translate('From Semester')?>
				</td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->FromSemester;?>
				</td>
				<td><?php echo $this->translate('To Semester')?>
				</td>
				<td><?php echo $this->lobjMarksdistributionmasterForm->ToSemester;?>
				</td>
			</tr>
			<tr>
				<td colspan="3"></td>
				<td align="right"><?php echo $this->lobjMarksdistributionmasterForm->Copy; ?>
					<?php echo $this->lobjMarksdistributionmasterForm->Clear; ?></td>
			</tr>
		</table>
	</fieldset>








</Form>

