<?php
//get locale
$registry = Zend_Registry::getInstance();
$locale = $registry->get('Zend_Locale');
$this->locale = $locale->toString();

if($locale == 'ar_YE'){
	$this->direction = "rtl";
	$this->float = "right";
	$locale = 'ar';
}else{
	$this->direction = "ltr";
	$this->float = "left";
	$locale = 'en';
}
$this->applicantSession = Zend_Registry::get('applicant');
$lobjinitialconfigModel = new GeneralSetup_Model_DbTable_Initialconfiguration(); 
$larrInitialSettings = $lobjinitialconfigModel->fnGetInitialConfigDetails(1);
$this->College = empty($larrInitialSettings['CollegeAliasName']) ? "College":$larrInitialSettings['CollegeAliasName'];
$this->Department =  empty($larrInitialSettings['DepartmentAliasName']) ? "Department":$larrInitialSettings['DepartmentAliasName'];
$this->Subject = empty($larrInitialSettings['SubjectAliasName']) ? "Subject":$larrInitialSettings['SubjectAliasName'];
$this->Course = empty($larrInitialSettings['CourseAliasName']) ? "Course":$larrInitialSettings['CourseAliasName'];
$this->Program = empty($larrInitialSettings['ProgramAliasName']) ? "Program":$larrInitialSettings['ProgramAliasName'];
$this->Branch = empty($larrInitialSettings['BranchAliasName']) ? "Branch":$larrInitialSettings['BranchAliasName'];
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xml:lang="<?php echo $this->locale; ?>"
	dir="<?php echo $this->direction; ?>">
<head>

<!-- ///////////////////////// DOJO ////////////////////////// -->
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/dojo/dojo/dojo.js" djConfig="parseOnLoad: true,locale:'<?php echo $locale;?>'"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/dojo/dojo/nls/dojo_<?php echo $locale;?>.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/jquery-1.7.2.min.js" ></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/jquery-ui-1.8.21.custom.min.js" ></script>
<link rel="stylesheet" type="text/css" href="<?php  echo $this->baseUrl();?>/css/jqueryui/smoothness/jquery-ui-1.8.21.custom.css" />
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker/datepicker.js" djConfig="parseOnLoad: true,locale:'<?php echo $locale;?>'"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker/eye.js" djConfig="parseOnLoad: true,locale:'<?php echo $locale;?>'"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker/utils.js" djConfig="parseOnLoad: true,locale:'<?php echo $locale;?>'"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker/layout.js?ver=1.0.2" djConfig="parseOnLoad: true,locale:'<?php echo $locale;?>'"></script>

<link rel="stylesheet" type="text/css" href="<?php  echo $this->baseUrl();?>/js/dojo/dijit/themes/claro/claro.css" />
<link rel="stylesheet" type="text/css" href="<?php  echo $this->baseUrl();?>/js/dojo/dojo/resources/dojo.css" />
<link rel="stylesheet" type="text/css" href="<?php  echo $this->baseUrl();?>/js/dojo/dojox/grid/enhanced/resources/claro/EnhancedGrid.css" />
<link rel="stylesheet" type="text/css" href="<?php  echo $this->baseUrl();?>/js/dojo/dojox/grid/enhanced/resources/EnhancedGrid_rtl.css" />
<link rel="stylesheet" type="text/css" href="<?php  echo $this->baseUrl();?>/js/dojo/dojox/grid/enhanced/resources/Pagination.css" />
<link rel="stylesheet" media="screen" type="text/css" href="<?php  echo $this->baseUrl();?>/css/colorpicker.css" />

<!-- ///////////////////////// DOJO ////////////////////////// -->
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/layout.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/usty/simpletree.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/usty/topmenu.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/usty/onlineapplication.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/usty/style.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/usty/left-menu.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/datepicker/datepicker.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/datepicker/layout12.css'); ?>
<?php
if($this->direction == 'rtl'){
	echo "<style>";
	echo "ul.potato-menu li.potato-menu-item {
	 				float:right;
				}";
	echo "#language{
	 				left:10px;
	 			}";

	echo "#appTitle{
	 				left: 15px;
					top: 25px;
	 			}";

	echo "#main-content{
						margin-right: 200px;
				}";

	echo "div.toolbar-button {
				float:left;
				text-align: left;
				}";

	echo "</style>";
}else{
	echo "<style>";
	echo "ul.potato-menu li.potato-menu-item {
	 				float:left;
				}";
	echo "#language{
	 				right:10px;
	 			}";

	echo "#appTitle{
	 				right: 15px;
					top: 25px;
	 			}";

	echo "#main-content{
						margin-left: 200px;
				}";

	echo "div.toolbar-button {
				float:right;
				text-align: right;
				}";

	echo "</style>";
}

?>
<body class="claro">
<div id="container">
		<div id="header">
			<div id="logo"></div>
			<div id="appTitle"><?php echo $this->translate(APPLICATION_TITLE);?></div>
		</div>
	
		<div id="menu" style="">
			<div id="language">
			
		<a href = "<?php echo $this->baseUrl();?>/onlineapplication/login"><span style="font-weight:bold;font-size:12px;color:#008000"><u>Home</u></span></a>
                <?php if(isset($this->applicantSession->IdApplicant)){ ?>
                <a href = "<?php echo $this->baseUrl();?>/onlineapplication/logout"><span style="font-weight:bold;font-size:12px;color:#008000"><u>Logout</u></span></a>
                <?php } ?>
			&nbsp;&nbsp <?php echo $this->translate("Language"); ?>: 
				<select
					style="width: 80px;" onchange="window.location = '?lang=' + this.options[this.selectedIndex].value">
						<option value="ar"
							<?php echo $this->locale=="ar_YE"?"selected='selected'":""; ?>>Arabic
						</option>
						<option value="en"
							<?php echo $this->locale=="en_US"?"selected='selected'":""; ?>>English
						</option>
				</select>

			</div>
</div></br>
		<div id="body">

			<!-- Begin Section Content-->
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
				<tbody>
					<tr>
						<td rowspan="2" valign="top">

						</td>
						<td valign="top">

							</div>
						</td>
					</tr>
					<tr>
						<td valign="top">
							<table width="100%" cellpadding="0" cellspacing="0" border="0">
								<tbody>
									<tr>
										<td valign="top"><?php echo $this->layout()->content; ?></td>
									</tr>
								</tbody>
							</table>
						</td>
					</tr>
				</tbody>
			</table>
			<!-- End Section Content-->
		</div>
		<div id="footer"><!-- Footer start --> <?php echo $this->translate("Copyright"); ?>&copy;<?php echo $this->translate(APPLICATION_ENTERPRISE) ;?> 
		<!-- Footer end --></div>
	</div>
</body>
</html>