<head>
<style>
.makebold {
	font-weight: bold;
}
</style>
<script>
dojo.addOnLoad(function(){
	//dijit.byId('field23').set('value','');
	//dijit.byId('field23').set('placeHolder','Select');
        //dijit.byId('field27').set('value','');
	//dijit.byId('field27').set('placeHolder','Select');

});

function AutoFillNextEditableDropDown(EditableDropDownId,JSONText){
	dijit.byId(EditableDropDownId).setValue("");
	var ddwidget = dijit.byId(EditableDropDownId);
	ddwidget.setAttribute('disabled', false);
        var options = {
					label:"name",
					identifier:"key",
					items:JSONText
				  };
        ddwidget.store = new dojo.data.ItemFileReadStore( { data: options } );
}



 function formsubmit() {
        var flag=true;
        var totalData = "<?php echo count($this->finalResult); ?>";
        for(var i=1;i<=totalData;i++) {
         if ($('#cb_'+i).is(':checked')) {
            var remarksvalue = $.trim($('#rm_'+i).val());
            var finalvalue = $.trim($('#fm_'+i).val());
            if(remarksvalue=='' ||  finalvalue=='' ) { flag=false;  }
        }
        }

        if(flag==false) {
                    alert('Remarks and Final Marks cannot be left blank.');
        } else {
                    $('#savedata').val('submitdata');
                    document.searchstudents.submit();
        }

 }

 function formreject() {
        var flag=true;
        var totalData = "<?php echo count($this->finalResult); ?>";
        for(var i=1;i<=totalData;i++) {
         if ($('#cb_'+i).is(':checked')) {
            var remarksvalue = $.trim($('#rm_'+i).val());
            var finalvalue = $.trim($('#fm_'+i).val());
            if(remarksvalue=='' ||  finalvalue=='' ) { flag=false;  }
        }
        }

        if(flag==false) {
                    alert('Remarks and Final Marks cannot be left blank.');
        } else {
                    $('#savedata').val('rejectdata');
                    document.searchstudents.submit();
        }
 }



 function positivevalue1(val1, val2 ,val3) {
     var TotalMarks =  parseInt(val3);
     var value1 = $('#'+val2).val();


      if((isNaN(value1))){
           $('#'+val2).val('');
           alert('Please insert numeric value in Final Marks');
           return false;
       }

     if(value1<0 || value1>TotalMarks ) {
         $('#'+val2).val('');
         alert("Final Marks should be postive and less than Total Marks");
         return false;
     }

 }

 function getCheckedValue (val1, val2, val3 ) {

     if ($('#'+val2).is(':checked')) {
            var remarksvalue = $('#rm_'+val3).val();
            var finalvalue = $('#fm_'+val3).val();
            if(remarksvalue=='' ||  finalvalue=='' ) { alert('Remarks and Final Marks cannot be left blank.');  }
     }

 }

function checkoneresitselected(val) {

        var chks = document.getElementsByName('resitchk[]');
	var hasChecked = false;
	for (var i = 0; i < chks.length; i++)
	{
		if (chks[i].checked)
		{
			hasChecked = true;
			break;
		}
	}

	if (hasChecked == false)
	{
		alert("Please select at least one.");
		hasChecked = false;
	}
	//return hasChecked;

        if(hasChecked==true) {

          if(val=='approve') {  formsubmit(); }
          else if(val=='reject') { formreject();  }

        }
}





</script>
</head>


<div id="target">
	<form name="searchstudents" id="searchstudents" method="post">
		<input type="hidden" name="savedata" id="savedata" value="searchdata">
		<fieldset>
			<legend>
				<?php echo $this->translate("Exam Resit Marks Approval Add");?>
			</legend>

			<table class="table" width="100%">

				<tr>

					<td width="25%" class="makebold"><?php echo $this->translate("Application ID");?>
					</td>
					<td width="25%"><?php echo $this->resultResit[0]['ExaminationResitApplicationCode'];?>
					</td>

					<td width="25%" class="makebold"><?php echo $this->translate("Student ID");?>
					</td>
					<td width="25%"><?php echo $this->resultResit[0]['StudentCode'];?>
					</td>

				</tr>

				<tr>
					<td width="25%" class="makebold"><?php echo $this->translate('Semester');?>
					</td>
					<td width="25%"><?php echo $this->resultResit[0]['SemesterCode'];?>
					</td>

					<td class="makebold"><?php echo $this->translate('Program');?></td>
					<td><?php echo $this->resultResit[0]['ProgramName'];?></td>
				</tr>

				<tr>
					<td width="25%" class="makebold"><?php echo $this->translate('Examiner1');?>
					</td>
					<td width="25%"><?php echo $this->lobjform->field23;?></td>

				</tr>


			</table>

		</fieldset>
		<br />

		<fieldset>

			<table class="table" width="100%" cellpadding="5" cellspacing="1">
				<form>

					<tr>
						<th><?php echo $this->translate('Course');?></th>
						<th><?php echo $this->translate('Component');?></th>
						<th><?php echo $this->translate("Detail Component");?>
						</th>
						<th><?php echo $this->translate("Old Marks");?></th>
						<th><?php echo $this->translate("New Marks");?>
						</th>
						<th><?php echo $this->translate("Total Marks");?>
						</th>
						<th><?php echo $this->translate("Remarks");?></th>
						<th><?php echo $this->translate("Final Marks");?>
						</th>
						<th><?php echo $this->translate("Approve/Reject");?></th>
					</tr>


					<?php if (count($this->finalResult)) {
						$i=1;
						foreach ($this->finalResult as $lobjprogram ) {
          ?>



					<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
						<input type="hidden" name="IdExaminationResitApplicationMarks[]"
							id="IdExaminationResitApplicationMarks"
							value="<?php echo $lobjprogram['IdExaminationResitApplicationMarks'];?>">
						<input type="hidden" name="IdStudent" id="IdStudent"
							value="<?php echo $lobjprogram['IdStudent'];?>">
						<input type="hidden" name="IdCourse" id="IdCourse"
							value="<?php echo $lobjprogram['IdCourse'];?>">

						<input
							name="CTY_<?php echo $lobjprogram['IdExaminationResitApplicationMarks'];?>"
							id="cty_<?php echo $i; ?>" type="hidden"
							value="<?php echo $lobjprogram['IdComponent'];?>">
						<input
							name="CIT_<?php echo $lobjprogram['IdExaminationResitApplicationMarks'];?>"
							id="cit_<?php echo $i; ?>" type="hidden"
							value="<?php echo $lobjprogram['ComponentItem'];?>">

						<td><?php echo $lobjprogram['SubjectName'];?></td>
						<td><?php echo $lobjprogram['ComponentName'];?></td>
						<td><?php echo $lobjprogram['MainSubComponentName'];?></td>
						<td><input
							name="OM_<?php echo $lobjprogram['IdExaminationResitApplicationMarks'];?>"
							id="om_<?php echo $i; ?>" readonly="readonly"
							dojoType="dijit.form.TextBox" type="text"
							value="<?php echo $lobjprogram['OldMarks'];?>"
							style="width: 50px;">
						</td>

						<td><input type="text" readonly="readonly"
							value="<?php echo $lobjprogram['NewMarks'];?>"
							dojoType="dijit.form.TextBox">
						</td>

						<td><input readonly="readonly" dojoType="dijit.form.TextBox"
							type="text" value="<?php echo $lobjprogram['TotalMarks'];?>"
							style="width: 50px;">
						</td>


						<td><input
						<?php if($this->larrresultApplicationEntryStatus[0]['Status']=='243' || $this->larrresultApplicationEntryStatus[0]['Status']=='195') { ?>
							readonly="readonly" <?php } ?> id="rm_<?php echo $i; ?>"
							dojoType="dijit.form.TextBox" type="text"
							name="RM_<?php echo $lobjprogram['IdExaminationResitApplicationMarks'];?>"
							value="<?php echo $lobjprogram['EntryRemark'];?>">
						</td>

						<td><input
						<?php if($this->larrresultApplicationEntryStatus[0]['Status']=='243' || $this->larrresultApplicationEntryStatus[0]['Status']=='195') { ?>
							readonly="readonly" <?php } ?>
							name="FM_<?php echo $lobjprogram['IdExaminationResitApplicationMarks'];?>"
							id="fm_<?php echo $i; ?>" dojoType="dijit.form.TextBox"
							type="text"
							onkeyup="positivevalue1(this.value,this.id,'<?php echo $lobjprogram['TotalMarks'];?>');"
							value="<?php echo $lobjprogram['FinalMarks'];?>"
							style="width: 50px;">
						</td>


						<td><input
						<?php if($lobjprogram['Status']=='243' || $lobjprogram['Status']=='195') { ?>
							checked="checked" readonly="readonly" <?php } ?>
							name="resitchk[]" id="cb_<?php echo $i; ?>"
							dojoType="dijit.form.CheckBox"
							OnClick="getCheckedValue(this.value,this.id,<?php echo $i; ?>);"
							value="1" type="checkbox">
						</td>

					</tr>
					<?php  $i++;
}
} ?>





					<tr>
						<td align="right" colspan="9">

							<?php if ($this->disableSubmit=='1') { ?>
							<?php if (count($this->finalResult)) { ?>
							<?php ///if($this->larrresultMA=='0')  { ?> <input type='button'
							class="NormalBtn"
							<?php if($this->larrresultApplicationEntryStatus[0]['Status']=='243' || $this->larrresultApplicationEntryStatus[0]['Status']=='195') { ?>
							disabled="disabled" <?php } ?> dojotype="dijit.form.Button"
							name="Approve" id="Approve"
							label="<?php echo $this->translate('Approve');?>" value='Approve'
							OnClick="checkoneresitselected('approve');" /> <?php //} else {  ?>

							<?php //} ?> <input type='button' class="NormalBtn"
							<?php if($this->larrresultApplicationEntryStatus[0]['Status']=='243' || $this->larrresultApplicationEntryStatus[0]['Status']=='195') { ?>
							disabled="disabled" <?php } ?> dojotype="dijit.form.Button"
							name="Reject" id="Reject"
							label="<?php echo $this->translate('Reject');?>" value='Reject'
							OnClick="checkoneresitselected('reject');" /> <?php  } ?>
							<?php } else {  ?>
							<span style="color: red"><?php echo $this->translate("Sorry, Student's Profile Status is not eligible for Exam Resit Marks Approval.");?></span>
							<?php } ?>


							<input
							type='button' class="NormalBtn" dojotype="dijit.form.Button"
							label="<?php echo $this->translate('Back')?>" value='click'
							onclick="window.location.href='<?php echo $this->url(array('module'=>'examination','controller'=>'resitmarksapproval', 'action'=>'index'),'default',true);?>';" />

						</td>

					</tr>

			</table>

		</fieldset>

	</form>
</div>



