<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
	background-image: url('/images/images/index/vector2.jpg');
}

.ade {
  background-color: #C4B65C;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
  


}

.topnav {
  overflow: hidden;
  background-color: #7A7346;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #AB9F5A;
  color: black;
}

.topnav a.active {
  background-color: #C8B858;
  color: white;
}

.topnav-right {
  float: right;
}
</style>
</head>
<body>

<!DOCTYPE html>
<html>
<head>
<style>
html, body {
  height: 100%;
}



img.two {
  height: 40%;
  width: 100%;
}
</style>
</head>
<body>
<img class="two" src="/images/images/index/usakti.jpg" width="500" height="500">

</body>
</html>

<div class="topnav">
  <a class="active" href="/homepage/homepage/view">Home</a>
  <a href="#krs">KRS</a>
  <a href="#transcript">Transcript</a>
  <div class="topnav-right">
    <a href="/index">Logout</a>
    
  </div>
</div>



<div style="padding-left:16px">
<p style="text-align:center;"><img src="/images/images/index/tif.jpg" alt="Logo" height="400" width="800"></p>
<br>
<div class="ade">
<h2>Teruntuk Bapak Agung Sediyono...</h2>
<table>
<tr>
<th><div style="border-bottom:2px solid #335595;">
<img class="img-responsive" alt="/images/images/index/agung.jpg" src="/images/images/index/agung.jpg">
<br><br>
<b>Ir. Agung Sediyono, MT, PhD</b>
</div>
</div></div></th>
<th>
<div style="text-align: justify; padding: 20px;">PEMROGRAMAN BERBASIS FRAMEWORK</p>
<p>Terima kasih banyak pak atas ilmu yang diberikan dalam 1 semester ini, terima kasih banyak
juga atas tawaran perbaikan nilai yang telah Bapak berikan kepada kami sehingga kami dapat
men-<em>explore</em> lebih jauh mengenai Pemrograman Berbasis Framework yang telah kita ambil pada
semester 5 ini. <br><br>

Maafkan kami jika saat perkuliahan kami tidak dapat mengikuti perkuliahan dengan baik,
semoga sistem yang telah kami buat sekiranya mendekati apa yang seharusnya kami rancang dalam
kuliah Pemrograman Berbasis Framework ini. <br><br>

Semoga ilmu yang telah Bapak berikan dapat bermanfaat kepada kami, dan Bapak terus diberikan
kesehatan dan kesuksesan mendatang, Amin YRA.

 <br><br>
 
 Regards,<br>
Mahasiswa Sistem Informasi Angkatan 2017<br>

</p>

</th>
</tr>
</table></div>

<br><br><br><br>
<div class="ade">
<h2>
Sekilas Mengenai Sistem Informasi Pemrograman Berbasis Framework Angkatan 2017</h2>

<b>Assalamu'alaikum Wr. Wb.<br>
Selamat datang di website Sistem Informasi PBF. <br>
<br>
Dalam website ini terdapat menu Referensi, Kurikulum, Penjadwalan, KRS, dan Transcript.</b>

<div style="text-align: justify;">

<br>
<br>

<b> 
Di dalam Referensi, user dapat men-input data untuk seluruh atribut yang ada di dalam sistem yang
telah di buat, meliputi nama dosen, nama mata kuliah, dan seluruh atribut yang nantinya akan 
terhubung ke bagian lain (Kurikulum, Penjadwalan, KRS, dan juga Transcript). Di dalam Referensi
nantinya akan ditampilkan juga data yang telah di-input berupa tabel yang berisikan data yang telah
di-input.
 
<br>
<br>

Di dalam Kurikulum, user dapat melihat data kurikulum apa saja yang datanya nantinya diambil dan
dihubungkan dari Referensi dan ditampilkan di dalam tabel. 
Cara melihat kurikulumnya adalah dengan melakukan fungsi <em>search</em> untuk mencari kurikulum
sesuai dengan semester yang diambil.
<br>
<br>

Di dalam Penjadwalan, user dapat mengelompokkan setiap mata kuliah yang akan diambil di tiap
semester, dan juga menjadwalkan jadwal setiap mata kuliah (seperti pada hari apa dan jam berapa)
pada setiap semester. Data mata kuliah didapatkan dari data yang di-input dari Referensi.

<br>
<br>

Di dalam KRS, user dapat mengisi KRS dengan cara meng-klik checkbox mata kuliah yang diinginkan 
sesuai dengan kurikulum yang telah ditetapkan, serta user tidak boleh mengambil KRS lebih dari 
24 SKS. Dan data mata kuliahnya diambil dari data yang di-input dari Referensi.
<br>
<br>

Di dalam Transcript, user dapat melihat hasil transcript yang telah di-input pada KRS, dan juga user
dapat men-download Transcript dalam bentuk PDF.
<br>
<br>

Sekian penjelasan singkat mengenai Sistem yang telah dibuat, lebih dan kurang kami mohon maaf
karena kami masih dalam tahap belajar. Terima kasih banyak atas perhatiannya.
<br>
<br>
<b>
<br>
<em>Wassalamualaikum wr. wb.</em><br>
</b></b>

&nbsp;</div>
</div></div><br><br><br><br>

</body>
</html>
