<?php
$tabArray = array(
		'1' => 'tab-one',
		'2' => 'tab-two',
);
?>
<head>
<script language='javascript'
	src='<?php echo $this->baseUrl(); ?>/js/jquery-1.4.3.js'></script>
<script type="text/javascript">
        dojo.addOnLoad(function (){
        });

        function fnToggleTabs(TabAction,CurrentTabId,NextTabId){
            if(TabAction == "Next"){
                var flag = Validateform(CurrentTabId);
                if(flag){
                    var mainTabContainerId = dijit.byId("mainTabContainer")
                    var tabContainerId = dijit.byId(NextTabId);
                    mainTabContainerId.selectChild(tabContainerId);
                }
            }else if(TabAction == "Back"){
                var mainTabContainerId = dijit.byId("mainTabContainer")
                var tabContainerId = dijit.byId(NextTabId);
                mainTabContainerId.selectChild(tabContainerId);
            }
        }
    </script>
<style type="text/css">
div.cabinet {
	width: 300px;
	background: url(<?php echo $this->baseUrl(); ?>/
	images /button.gif) 0 0 no-repeat;
	/*height: 100px;*/
	display: block;
	cursor: pointer;
}

div.cabinet div.MultiFile-wrap div.MultiFile-list {
	height: 70px;
	width: 600px;
	display: block;
	overflow: auto;
}

div.cabinet div.MultiFile-wrap div.MultiFile-list div.MultiFile-label a.MultiFile-remove
	{
	background: url(<?php echo $this->baseUrl();
	?>/
	images
	/delete.png)0
	0
	no-repeat;
}

div.cabinet input.file {
	position: relative;
	width: auto;
	opacity: 0;
	-moz-opacity: 0;
	filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0 );
}
</style>
</head>
<body class="claro">
	<fieldset>
		<legend>
			<?php echo $this->translate("Assessment Type Setup"); ?>
		</legend>
		<table>
			<tr>
				<td>
					<div id="mainTabContainer" dojoType="dijit.layout.TabContainer"
						doLayout="false" tabPosition="top"
						style="width: 1100px; height: auto">
						<!-- Partial start here for Assessment type tab -->
						<?php echo $this->partial("assessmenttype/assessmenttype.phtml", array('lobjassessmentForm' => $this->lobjassessmentForm,'assessmenttypeList' => $this->assessmenttypeList,'defaultlanguage' => $this->defaultlanguage)); ?>
						<!-- Partial close here for Assessment type tab -->

						<!-- Partial start here for Assessment item tab -->
						<?php echo $this->partial("assessmenttype/assessmentitem.phtml",array('lobjassessmentForm' => $this->lobjassessmentForm,'assessmentItemList' => $this->assessmentItemList,'defaultlanguage' => $this->defaultlanguage))?>
						<!-- Partial close here for Assessment item tab -->
					</div>
				</td>
			</tr>
		</table>
	</fieldset>
