<script>


$(function() {
	
	$( "#dialog-box" ).dialog({
        autoOpen: false,
        width: 650,
        modal: true,
        buttons: {
            "Confirm": function() {
            	
            	 
            		var approver = $("#approveby option:selected").val();
                 	if(approver==0){
                		alert('Please select Approved by');
                 	}else{

                 		$("#ApprovedBy").val(approver);	
                 		$("#form1").submit();                 		
                 	}
				 
            	        	
            },
            Cancel: function() {
                $( this ).dialog( "close" );
            }
        }
    });
		
});


function showLoading(element_loadmark){	
	$(element_loadmark).hide();
	$(element_marked).after("<div id='loadimg'><img src='/images/spinner.gif' width='30' heigth='30' /></div>");
}

function hideLoading(element_loadmark){
	$('#loadimg').remove();	
	$(element_loadmark).show();
}

function validate(){
	var valid = true;	
	$('input[class="entry"]').each(function(){	   
		 if($(this).val()==''){			 
			 return valid = false;
		 }	    
	});

}

function validate_numeric(){
	var valid = true;	
	$('input[class="entry"]').each(function(){	
		entrymark = $(this).val();
		if(entrymark != ''){
		if($.isNumeric( entrymark )==false){ 
			return valid = false;
		}}
	});
	return valid;	
}




</script>

<script>

$(function () {

	$( "#dialog-search" ).dialog({
        autoOpen: false,
        width: 650,
        modal: true,
        buttons: {
            "Search": function() {   
    			$("#myform").submit();         	
            },
            "Cancel": function() {
                $( this ).dialog( "close" );
            }
        }
    });	
	
});

function searchBox(){
	$( "#dialog-search" ).dialog('open');	
}


function approval(){
	 
	$( "#dialog-box" ).dialog('open');	
}

function back(role){
	if(role==1){//admin
		window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-entry','action'=>'index'), 'default', true);?>";
	}else{
		window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-entry','action'=>'group-list'), 'default', true);?>";
	}
}
</script>



<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
		     <li>							
					<a href="#" onClick="approval()">
						<span class='process'></span>Approve</a>				
			</li>	
		    <li>							
					<a href="#" onClick="searchBox()">
						<span class='search'></span>Search</a>				
			</li>			
			<li>							
					<a href="#" onClick="back('<?php echo $this->role; ?>')">
						<span class='back'></span>Back</a>				
			</li>	
			
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br>
<div style="width:100%;">

<table class="table" width="600px" cellpadding="5" cellspacing="1" border="0">
	<tr>
		    <th width="25%"><?php echo $this->translate("Programme Name"); ?></th>   
		    <td><?php echo $this->program['ArabicName'];?></td>   
	</tr>
	<tr>
		    <th width="25%"><?php echo $this->translate("Branch Name"); ?></th>   
		    <td><?php echo $this->branch['BranchName'];?></td>   
	</tr>
	<tr>
		    <th width="25%"><?php echo $this->translate("Semester Name "); ?></th>   
		    <td><?php echo $this->semester[0]['SemesterMainName'];?></td>   
	</tr>
	<tr>
		    <th><?php echo $this->translate("Subject Name "); ?></th>   
		    <td><?php echo $this->subject['BahasaIndonesia'];?> (<?php echo $this->subject['SubCode'];?>)</td>   
	</tr>
	<tr>
		    <th width="25%"><?php echo $this->translate("Course Group Name "); ?></th>   
		    <td><?php echo $this->group["GroupName"].' - '.$this->group["GroupCode"];;?></td>   
	</tr>
	<tr>
		    <th width="25%"><?php echo $this->translate("Coordinator"); ?></th>   
		    <td><?php echo $this->group["FullName"];?></td>   
	</tr>
	<tr>
		    <th width="25%"><?php echo $this->translate("Display Mark Date"); ?></th>   
		    <td><?php echo (isset($this->publish["pm_date"])) ? date("d-m-Y",strtotime($this->publish["pm_date"])):'-';?></td>  
	</tr>
</table>
<br>



<?php 
if(count($this->students)>0) {

	
		 
	 
?>

<form id="form1" method="post" >

<input type="hidden" name="idSemester" id="idSemester" value="<?php echo $this->idSemester;?>"></input>
<input type="hidden" name="idProgram" id="idProgram" value="<?php echo $this->idProgram;?>"></input>
<input type="hidden" name="idSubject" id="idSubject" value="<?php echo $this->idSubject;?>"></input>
<input type="hidden" name="idBranch" id="idBranch" value="<?php echo $this->idBranch;?>"></input>
<input type="hidden" name="idGroup" id="idGroup" value="<?php echo $this->idGroup;?>"></input>
<input type="hidden" name="ApprovedBy" id="ApprovedBy" ></input>
<?php 

$nComp=count($this->rs_component);
$rowspan= 'rowspan=2';
$compitem=false;
foreach ($this->rs_component as $value) {
	if ($value['nitem']>0) {
		$rowspan= 'rowspan=3';
		$compitem=true;
	}
}

?>
<table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">	  
	  <tr>
	    <th <?php echo $rowspan; ?> width="25px">&nbsp;</th>
	    <th <?php echo $rowspan; ?>><?php echo $this->translate("Student Name")?></th>
	    <th <?php echo $rowspan; ?>><?php echo $this->translate("Student ID/NIM")?></th>
	  
	    <?php foreach ($this->rs_component as $value) {
			    	$component_item=$value['item'];
			    	$idmark=$value['IdMarksDistributionMaster'];
			    	$nitem=$value['nitem'];
			    	if($nitem>0){
			    		 
			    		$colspan = 2+abs($nitem)*2;
			    		
			    		
			    	}else{
			    		 
			    		$colspan = 2;
			    	}
	    	?>
	    	
	    <th  align="center" colspan="<?php echo $colspan;?>">
	    		<?php echo $value["component_name"] ?><br>
	    		<?php if($nitem==0){?>
	    		Verified by : <?php echo $value['VerFullName']; }?>
	    </th>
		<input type="hidden" name="IdMarksDistributionMaster<?php echo $idmark ?>" id="IdMarksDistributionMaster<?php echo $idmark ?>" value="<?php echo $idmark;?>">
		<input type="hidden" name="total_item<?php echo $idmark ?>" id="total_item<?php echo $idmark?>" value="<?php echo $nitem;?>">
		
		<?php }
		?>
		<th <?php echo $rowspan; ?> width="25px"><?php echo $this->translate('Total Mark')?></th>
	   <th <?php echo $rowspan; ?> width="25px"><?php echo $this->translate('Grade')?></th>
	   <th <?php echo $rowspan; ?> width="25px"><?php echo $this->translate('Pass')?></th>
	   <th <?php echo $rowspan; ?> width="25px"><?php echo $this->translate('Status')?></th>
	   <tr> 
	      <?php  
	      foreach ($this->rs_component as $value) {
	      	
	      	$idmark=$value["IdMarksDistributionMaster"];
	      
			if($compitem){
				$component_item=$value['item'];
				$nitem=$value['nitem'];
				if ($nitem>0) {
				      $x=1;
				      
				      foreach($component_item as $item){
							$idmarkdetail=$item["IdMarksDistributionDetails"];
							$colspandetail = 2; ?>	
				      <th  align="center" colspan="<?php echo $colspandetail;?>">
				       <?php echo $item["ComponentName"];?><br>
				       <?php if($nitem>0){?>
	    					Verified by : <?php echo $item['VerFullName']; }?>
				       </th>
				       <input type="hidden" name="IdMarksDistributionDetail<?php echo $idmark.$x ?>" id="IdMarksDistributionDetail<?php echo $idmarkdetail ?>" value="<?php echo $idmarkdetail;?>">
				
				      
			     <?php $x++; }//end foreach ?>
			     		
	     		<th align="center" colspan="2">Total Mark</th>
	     		<?php } else {?>
	     			<th align="center" colspan="2">&nbsp;</th>
	     		<?php } ?>
	     		
	<?php }else{ ?>
		  	<th align="center">
		  	      Student Raw Mark <br>
		  	     (Total Mark : <?php echo $value["Marks"];?>)
		  	     <input type="hidden" size="3" name="MarksTotal" id="MarksTotal<?php echo $idmark?>" value="<?php echo $value["Marks"];?>">
		  	</th>
	        <th align="center">Mark 
	        <br>(Percentage : <?php echo $value["Percentage"];?> %)<input type="hidden" size="3" name="Percentage" id="Percentage<?php echo $idmark?>" value="<?php echo $value["Percentage"];?>"></th>
		  <?php } //end if  ?>
	      
	 
	 <?php 
	   	 }?> 
	   	 
	   	 </tr>
	 	<tr>
	 	<?php if ($compitem>0) {
	 	
		 		foreach ($this->rs_component as $value) {
		      		$component_item=$value['item'];
					$nitem=$value['nitem'];
		      		$idmark=$value["IdMarksDistributionMaster"];
		      	 	if ($nitem>0) {
						$x=1;
		     			foreach($component_item as $item){
							
							 ?>	
		     		 
		     				<th>Total Mark : (<?php echo $item["Weightage"];?>)
		     			    <input type="hidden" size="3" name="MarksTotal" id="MarksTotal<?php echo $idmark.$x; ?>" value="<?php echo $item["Weightage"];?>">		     
		     			    </th>
		     				<th  align="center">
		     				Percentage : (<?php echo $item["Percentage"];?>%)
		     			    <input type="hidden" size="3" name="Percentage" id="Percentage<?php echo $idmark.$x; ?>" value="<?php echo $item["Percentage"];?>">
		     				</th>
		     		
	     		   		
		      	<?php  $x++;}
		      		 	?>
		      		 	<th>Total Mark : (<?php echo $value["Marks"];?>)
		     			    <input type="hidden" size="3" name="MarksTotal" id="MarksTotal<?php echo $idmark; ?>" value="<?php echo $value["Marks"];?>">		     
		     			    </th>
		     				<th  align="center">
		     				Percentage : (<?php echo $value["Percentage"];?>%)
		     			    <input type="hidden" size="3" name="Percentage" id="Percentage<?php echo $idmark; ?>" value="<?php echo $value["Percentage"];?>">
		     				</th>
		      		 	
		      		 	<?php 
		      		} else {
						
				?>			<th>Total Mark : (<?php echo $value["Marks"];?>)
		     			    <input type="hidden" size="3" name="MarksTotal" id="MarksTotal<?php echo $idmark; ?>" value="<?php echo $value["Marks"];?>">		     
		     			    </th>
		     				<th  align="center">
		     				Percentage : (<?php echo $value["Percentage"];?>%)
		     			    <input type="hidden" size="3" name="Percentage" id="Percentage<?php echo $idmark; ?>" value="<?php echo $value["Percentage"];?>">
		     				</th><?php 
					}
		      	}
	 
	 	  } ?>
	 	</tr>
	    
	    	 
	  <?php 
		$i=1;	
		foreach($this->students as $student){
			$disabled='';	
			if ($student['mark_approveby']!='')	 $disabled="disabled";
	  ?>
	  <tr>
	    <td><?php echo $i;?></td>
		<td><?php echo $student["appl_fname"].' '.$student["appl_mname"].' '.$student["appl_lname"];?></td>
		<td><?php echo $student["registrationId"];?>		
		<input type="hidden" name="IdStudentRegistration" id="IdStudentRegistration<?php echo $i;?>" value="<?php echo $student["IdStudentRegistration"]; ?>">
 
		</td>
		 
	    <?php 	
	    $publishDb= new Examination_Model_DbTable_PublishMark();
	    foreach ($this->rs_component as $component) {   
			$idmark=$component["IdMarksDistributionMaster"];
			$mark=$student[$idmark];
			$publishs = $publishDb->isPublished($this->idProgram, $this->idSemester, $this->idSubject, $this->idGroup,$idmark);
			$publish="";
            if ($publishs) $publish="1";
		    if($component['nitem']>0){
		    	$x=1;
		    	$detailsMarkDB = new Examination_Model_DbTable_StudentDetailsMarkEntry();
			    foreach($component['item'] as $item){	
					  	    
			    	 $idmarkdetail=$item["IdMarksDistributionDetails"];
			    	//cari dalam mark details IdStudentMarksEntry
			    	if($student[$idmark]["IdStudentMarksEntry"]!=''){		    		
				    	
				    	$itemMark = $detailsMarkDB->getItemMark($mark["IdStudentMarksEntry"],$idmarkdetail);
				    	$itemMarkObtained = $itemMark["MarksObtained"];
				    	$FinalMarksObtained = $itemMark['FinalMarksObtained'];
			    	}else{
			    		$itemMark["IdStudentMarksEntryDetail"]='';
			    		$itemMarkObtained='';
			    		$FinalMarksObtained='';
			    		
			    	}
		
	            	 
		            ?>
		             <td align="center"><?php echo $itemMarkObtained;?></td>
			    	<?php  
	            	//echo $this->idstaff.'='.$component['entrier'];
	            	if($FinalMarksObtained=='' || $publish=='' ){ //approve x boleh ubah lagi markah
						echo "<td align='center'>";
	            	}else{
						$status="";
					 
						$bgcolor="white";
						if ( $item['verifier']!=$this->idstaff ) {
							$disabled="disabled";
							$bgcolor="";
						}
						if ($itemMark['MarksEntryStatus']==411) {
							 $status="checked";
							 $bgcolor="";
							 }
						?>
	            		 <td  align="center"  bgcolor="<?php echo $bgcolor;?>">
	            		<input type="checkbox"  class="check" name="verifyitem[<?php echo $student['IdStudentRegistration']?>][<?php echo $idmark?>][<?php echo $idmarkdetail?>]" id="verify<?php echo $i.$idmark.$idmarkdetail?>" <?php  echo $disabled;?> <?php  echo $status;?> value="<?php echo $itemMark["IdStudentMarksEntryDetail"];?>">
	            		<?php 
	            	}  echo $FinalMarksObtained;?></td>
		          		    	
			    
		    <?php $x++; }
		    
		         //end foreach
		   			?> 
		   			  <td align="center"><?php echo $mark["TotalMarkObtained"]; ?></td>
		   			  <td align="center"><?php echo $mark["FinalTotalMarkObtained"]; ?>
		     </td>
		   			<?php 
		    }else{ ?>
		     	 <td align="center">
	            
	         <?php echo $mark["TotalMarkObtained"];?></td>
		      <?php  
	            	//echo $this->idstaff.'='.$component['entrier'];
	            	if($mark["TotalMarkObtained"]=='' || $publish==''){ //approve x boleh ubah lagi markah
						echo "<td align='center'>";
	            	}else{
						$status='';
						$bgcolor="white";
						if ( $component['verifier']!=$this->idstaff ) {
							$disabled="disabled";
							$bgcolor="";
						}
						if ( $mark["MarksEntryStatus"]==411) {
							$status="checked";
							$bgcolor="";
							}
	            		?>
	            		<td align="center" bgcolor="<?php echo $bgcolor;?>">
	            		<input type="checkbox" class="check" name="verify[<?php echo $student['IdStudentRegistration']?>][]" id="verify<?php echo $i.$idmark?>" <?php  echo $disabled;?> <?php  echo $status;?> value="<?php echo $mark["IdStudentMarksEntry"]?>">
	            		<?php 
	            	}  echo $mark["FinalTotalMarkObtained"];?>
	            	</td>
		     
	    <?php }
	            ?>
	          
	            <?php 
	        }//end if else count item?>
	  
	  
	  <td align="center"><?php echo $student['final_course_mark'];?></td>
	  <td align="center"><?php echo $student['grade_name'];?></td>
	 <td align="center"><?php echo $student['grade_status'];?></td>
	  <td align="center"><?php echo $student['exam_status'];?></td>
	   </tr>
	  
	  <?php 
		$i++; }
	  ?>
	</table>
 
</form>

<?php }else{ //end if? 
echo $this->translate("No record of student attended this Exam");
}?>



</div>
<br>

<div id="dialog-box" title="<?php echo $this->translate("Approval Information"); ?>">
  <table>
   
  	<tr>
  		<td>Approved By</td>
  		<td width="5px">:</td>
  		<td>
  		<select name="approveby" id="approveby" >
  			<option value=0>Please Select</option>
  			<?php foreach($this->staff as $staff){
  				$status='';
  				if ($staff['IdStaff']==$this->idstaff) $status="selected";?>
  			<option value='<?php echo $staff["IdStaff"];?>' <?php echo $status ?>><?php echo $staff["FullName"];?></option>
  			<?php } ?>
  		</select>
  		</td>
  	</tr>
  	 
  </table>
</div>


<div id="dialog-search" title="<?php echo $this->translate("Search"); ?>">
<?php echo $this->form; ?>
</div>

