<form name = "datamhsform" method="post">
<style>
body {
 
 background-image: url('/images/images/index/vector2.jpg');
}
.ade {
 
 background-image: url('/images/images/index/penjadwalan.jpeg'); 
 
}
.salsa { 
  background-color: #ffffff;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
}
.topnav {
  overflow: hidden;
  background-color: #7A7346;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #AB9F5A;
  color: black;
}

.topnav a.active {
  background-color: #C8B858;
  color: white;
}

.topnav-right {
  float: right;
}

input[type="submit"] {
  background-color: #575445;
  color: black;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
 width: 90px; 
    padding: 20px; 
    cursor: 
    pointer; 
    box-shadow: 6px 6px 5px; #999; 
    -webkit-box-shadow: 6px 6px 5px #575445; 
    -moz-box-shadow: 6px 6px 5px #999; 
    font-weight: bold; 
    background: #B4A768; 
    color: #000; 
    border-radius: 10px; 
    border: 1px solid #999; 
    font-size: 100%;
}
</style>
</head>
<body>

<!DOCTYPE html>
<html>
<head>
<style>
html, body {
  height: 100%;
}



img.two {
  height: 40%;
  width: 100%;
}

}
</style>
</head>
</html>

<div class="topnav">
  <a  href="/homepage/homepage/view">Home</a>
 
  <a href="#referensi">Referensi</a>
   <a href="#Kurikulum" >Kurikulum</a>
  <a href="#penjadwalan" class="active">Penjadwalan</a>
  <a href="#krs">KRS</a>
  <a href="#transcript">Transcript</a>
 
  <div class="topnav-right">
    <a href="/index">Logout</a>
    
  </div>
</div>
</style>
 
<div class="salsa"><fieldset><legend> <?php echo "Group Info"?></legend>
<input type = "hidden" id= "id" name="id" value="<?php echo $this->jadwalan['id']?>">
<table>
<tr><th>SEMESTER</th>
<td><input type="text" name="semester" id= "semester" value="<?php echo $this->jadwalan['semester']?>">
<tr><th> PENJADWALAN AKTIVASI</th>
<td><input type="text" name="penjadwalanaktivasi" id= "penjadwalanaktivasi" value="<?php echo $this->jadwalan['penjadwalanaktivasi']?>">
<tr><th>KODE MK</th>
<td><input type="text" name="kodemk" id= "kodemk" value="<?php echo $this->jadwalan['kodemk']?>">
<tr><th>MATA KULIAH</th>
<td><input type="text" name="matakuliah" id= "matakuliah" value="<?php echo $this->jadwalan['matakuliah']?>">
<tr><th>DOSEN</th>
<td><input type="text" name="dosen" id= "dosen" value="<?php echo $this->jadwalan['dosen']?>">
<tr><th>RUANG</th>
<td><input type="text" name="ruang" id= "ruang" value="<?php echo $this->jadwalan['ruang']?>">
<tr><th>KAPASITAS KELAS</th>
<td><input type="text" name="kapasitas_kelas" id= "kapasitas_kelas" value="<?php echo $this->jadwalan['kapasitas_kelas']?>">
<tr><th>HARI</th>
<td><input type="text" name="hari" id= "hari value="<?php echo $this->jadwalan['hari']?>">
<tr><th>MULAI WAKTU</th>
<td><input type="text" name="mulai_waktu" id= "mulai_waktu" value="<?php echo $this->jadwalan['mulai_waktu']?>">
<tr><th>AKHIR WAKTU</th>
<td><input type="text" name="akhir_waktu" id= "akhir_waktu" value="<?php echo $this->jadwalan['akhir_waktu']?>">
<tr><td colspan="2">
</td></tr>
</div> 

<br><br>
<tr><td colspan="2">
<input type="submit" name = "save" value="save">
<input type="submit" name = "delete" value="delete">
<input type="submit" name = "update" value="update">
<input type="submit" name = "search" value="search">
</td></tr>
</table>
</form>
</div>
</fieldset>

 
<br><br><div class="salsa">
<legend><table border ="" width = "100%"><h1> Data Penjadwalan</h1><tr><th>SEMESTER</th><th>PENJADWALAN AKTIVASI</th><th>KODE MK</th><th>DOSEN</th><th>MATA KULIAH</th><th>RUANG</th><th>KAPASITAS KELAS</th><th>HARI</th><th>MULAI WAKTU</th><th>AKHIR WAKTU</th></legend>
<?php foreach($this-> datajdw as $mhs) {?> 
<Tr><td><?php echo $mhs['semester'];?></td>
  <td><?php echo $mhs['penjadwalanaktivasi'];?></td>
  <td><?php echo $mhs['kodemk'];?></td>
  <td><?php echo $mhs['dosen'];?></td>
  <td><?php echo $mhs['matakuliah'];?></td>
  <td><?php echo $mhs['ruang'];?></td>
  <td><?php echo $mhs['kapasitas_kelas'];?></td>
  <td><?php echo $mhs['hari'];?></td>
  <td><?php echo $mhs['mulai_waktu'];?></td>
  <td><?php echo $mhs['akhir_waktu'];?></td></Tr>
<?php }?>
  </table> 
