<form name = "datamhsform" method="post">

<style>
.nihaya {
  background-color: #C4B65C;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
}
</style>

<style>
/* Add a black background color to the top navigation */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}

.topnav a:hover {
  border-bottom: 3px solid red;
}

.topnav a.active {
  border-bottom: 3px solid red;
}
</style>
<br><br>

<div class="topnav">
  <a href="/pelajaran/pelajaran/view">Matakuliah</a>
  <a href="/siswa/siswa/view">Mahasiswa</a>
  <a href="/dosen/dosen/view">Dosen</a>
  <a href="/ruangan/ruangan/view">Ruangan</a>
  <a href="/akademik/akademik/view">Tahun Akademik</a>
  <a href="/pengisian/pengisian/view">Batas Pengisian Krs</a>
  <a href="/penjadwalan/penjadwalan/view">Penjadwalan Aktivasi</a>
</div>

<br><br><div class="nihaya">
<fieldset><legend> <?php echo "Data Entry Referensi"?></legend>
<style>
/* Add a black background color to the top navigation */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}

.topnav a:hover {
  border-bottom: 3px solid red;
}

.topnav a.active {
  border-bottom: 3px solid red;
}
</style>
<br><br>




<input type = "hidden" id= "id" name="id" value="<?php echo $this->datapersonal['id']?>">
<table>
<tr><th>Penjadwalan Aktivasi</th>
<td><input type="date" name="penjadwalanaktivasi" id= "penjadwalanaktivasi" value="<?php echo $this->datapersonal['penjadwalanaktivasi']?>">
<tr><th>Kode MK</th>
<td><input type="text" name="kodemk" value="<?php echo $this->datapersonal['kodemk']?>">
<tr><th>Matakuliah</th>
<td><input type="text" name = "matakuliah" id="matakuliah" value="<?php echo $this->datapersonal['matakuliah']?>" >
<tr><th>SKS</th>
<td><input type="text" name = "sks" id="sks" value="<?php echo $this->datapersonal['sks']?>" >
<tr><th>Dosen</th>
<td><input type="text" name = "dosen" id="dosen" value="<?php echo $this->datapersonal['dosen']?>" >


<br><br>
<tr><td colspan="2">
<input type="submit" name = "save" value="save">
<input type="submit" name = "delete" value="delete">
<input type="submit" name = "update" value="update">
<input type="submit" name = "search" value="search">
</td></tr>
</table>
</form>
</div>
</fieldset>

<br><br><div class="nihaya">
<fieldset><legend><table class="table" border="1"><h1> Data Penjadwalan Aktivasi</h1><tr><th>Penjadwalan Aktivasi</th><th>Kode MK</th><th>Matakuliah</th><th>SKS</th><th>Dosen</th></legend><?php foreach($this->refmhs as $mhs) {?> 
<tr><td><?php echo $mhs['penjadwalanaktivasi'];?></td></th> 
<td><?php echo $mhs['kodemk'];?></td> 
<td><?php echo $mhs['matakuliah'];?></td>
<td><?php echo $mhs['sks'];?></td>
<td><?php echo $mhs['dosen'];?></td>
<?php }?>

  </table>