<head>
<script>
dojo.addOnLoad(function(){

	dijit.byId('field5').set('value','');
	dijit.byId('field5').set('placeHolder','Select');

	dijit.byId('field8').set('value','');
	dijit.byId('field8').set('placeHolder','Select');
	});
</script>
</head>
<body class="claro">
	<fieldset>
		<legend>
			<?php echo $this->translate("Student").' '.$this->translate("Subjects").' '.$this->translate("Search");?>
		</legend>
		<form
			action="<?php echo $this->baseUrl();?>/examination/cgpacalculation/index/search/1"
			method="POST">
			<table width="100%">
				<tr>
					<td><?php echo $this->translate("Student").' '.$this->translate("Name");?>
					</td>
					<td><?php echo $this->lobjform->field5;?></td>
					<td><?php echo $this->translate("Application Id");?></td>
					<td><?php echo $this->lobjform->field3;?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("I.C").' '.$this->translate("No");?>
					</td>
					<td><?php echo $this->lobjform->field2;?></td>
					<td><?php echo $this->translate("$this->Program");?></td>
					<td><?php echo $this->lobjform->field8;?></td>
				</tr>

				<tr>
					<td align="center" colspan="4"><?php echo $this->lobjform->Search;?>
						<?php echo $this->lobjform->Clear;?>
					</td>

				</tr>
			</table>
		</form>
	</fieldset>
	<br />


	<form name="studentsubjectmarks" method="POST">
		<fieldset>
			<table class="table" width="100%" cellpadding="5" cellspacing="1">
				<tr>
					<th><?php echo $this->translate("Student").' '.$this->translate("Name");?>
					</th>
					<th><?php echo $this->translate("Application").' '.$this->translate("ID.");?>
					</th>
					<th><?php echo $this->translate("IC").' '.$this->translate("No.");?>
					</th>
				</tr>
				<?php if (count($this->paginator)): ?>
				<?php foreach ($this->paginator as $lobjstudents): ?>
				<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
					<td><a
						href="<?php echo $this->baseUrl();?>/examination/cgpacalculation/newcgpacalculation/idapplicant/<?php echo $this->escape($lobjstudents['IdApplication']);?>"><?php print_r($this->escape($lobjstudents['FName'].' '.$lobjstudents['MName'].' '.$lobjstudents['LName']));?>
					</a></td>
					<td><?php echo $this->escape($lobjstudents['StudentId']);?></td>
					<td><?php echo $this->escape($lobjstudents['ICNumber']);?></td>
					<?php endforeach; ?>
					<?php endif; ?>
				</tr>
				<tr>
					<td colspan="8" align="right"><div class="pagination">
							<?php echo $this->paginationControl($this->lobjpaginator,'Sliding',
									'/partials/my_pagination_control.phtml'); ?>
						</div></td>
				</tr>
			</table>
		</fieldset>
	</form>


</body>
</html>
