<script type="text/javascript">
//---------------------------
//pls update this view to SIS your version is not work well
//------------------

function addRowToTable()
{

  var tbl = document.getElementById('tblComponent');
  var lastRow = tbl.rows.length; 

  // if there's no header row in the table, then iteration = lastRow + 1
  var iteration = lastRow-2;
  var row = tbl.insertRow(lastRow-1);
  document.getElementById('iteration').value = iteration
// left cell
  
  var min_mark = row.insertCell(0);
  var cw = document.createElement('input');
  cw.type = 'text';
  cw.name = 'ordercomponent' + iteration ;
  cw.id = 'ordercomponent'+ iteration;
  cw.size = 5;
  cw.value=iteration;
  min_mark.appendChild(cw);
  // left cell
  var cellLeft = row.insertCell(1);
  var textNode1 = document.createTextNode('');
  cellLeft.appendChild(textNode1);
  

  // select cell component name
  var component_id = row.insertCell(1);
  var ci = document.createElement('select');
  ci.name = 'component_id' + iteration;
  ci.options[0] = new Option('-- Sila Pilih --', '0');
     
  <?php $i=1; foreach ($this->components as $component){ ?> 
  ci.options[<?php echo $i;?>] = new Option('<?php echo $component["value"]?>', '<?php echo $component["key"]?>');
  <?php $i++; } ?>

  component_id.appendChild(ci);
  


  //component_total_mark
  var component_total_mark = row.insertCell(2);
  var ctm = document.createElement('input');
  ctm.type = 'text';
  ctm.name = 'component_total_mark' + iteration;
  ctm.id = 'component_total_mark'+ iteration;
  ctm.size = 20;
  
 // ctm.onkeypress = keyPressTest;
  ctm.onblur = onGetTotalMark;  
  component_total_mark.appendChild(ctm);

 
  //cw.onblur = onGetTotalPercentage;  
  //component_percentage.appendChild(cw);

  //component_percentage
  var component_percentage = row.insertCell(3);
  var cw = document.createElement('input');
  cw.type = 'text';
  cw.name = 'component_percentage' + iteration ;
  cw.id = 'component_percentage'+ iteration;
  cw.size = 20;

  cw.onblur = onGetTotalPercentage;  
  component_percentage.appendChild(cw);

  //minimum mark
  var min_mark = row.insertCell(4);
  var cw = document.createElement('input');
  cw.type = 'text';
  cw.name = 'min_mark' + iteration ;
  cw.id = 'min_mark'+ iteration;
  cw.size = 6;
  min_mark.appendChild(cw);
  //appeal
  var appeal = row.insertCell(5);
  var a = document.createElement('input');
  a.type = 'checkbox';
  a.name = 'appeal' + iteration;
  a.id = 'appeal'+ iteration; 
  appeal.appendChild(a);

  //resit
  var resit = row.insertCell(6);
  var r = document.createElement('input');
  r.type = 'checkbox';
  r.name = 'resit' + iteration;
  r.id = 'resit'+ iteration; 
  resit.appendChild(r);

  
//allow_null
  var allowNull = row.insertCell(7);
  var r = document.createElement('input');
  r.type = 'checkbox';
  r.name = 'allownull' + iteration;
  r.id = 'allownull'+ iteration; 
  allowNull.appendChild(r);
  
}

function keyPressTest(e, obj)
{
  var validateChkb = document.getElementById('chkValidateOnKeyPress');
  if (validateChkb.checked) {
    var displayObj = document.getElementById('spanOutput');
    var key;
    if(window.event) {
      key = window.event.keyCode; 
    }
    else if(e.which) {
      key = e.which;
    }
    var objId;
    if (obj != null) {
      objId = obj.id;
    } else {
      objId = this.id;
    }
    displayObj.innerHTML = objId + ' : ' + String.fromCharCode(key);
  }
}
function removeRowFromTable()
{
  
  
  var tbl = document.getElementById('tblComponent');
  var lastRow = tbl.rows.length;

  curval = document.getElementById('iteration').value;
 
  
  if (lastRow > 3){
	   tbl.deleteRow(lastRow - 2);  
	   document.getElementById('iteration').value = curval-1;
  } 
  
}



function onGetTotalMark(){

	 var tbl = document.getElementById('tblComponent');
	 var lastRow = tbl.rows.length - 3;

	 var i;
	 var total=0;		  
	    
	 for (i=1; i<=lastRow; i++) {
		 
    	 var aRow = document.getElementById('component_total_mark' + i);
    	 
		 rowVal = aRow.value;
		 total=total+Math.abs(rowVal);
  	}  
	  
	document.getElementById('total_mark').value = total;
	 	         
}


function onGetTotalPercentage(){

    	//get total percentage
	    var tbl = document.getElementById('tblComponent');
	    var lastRow = tbl.rows.length - 3;
	  
	    var i;
	    var total=0;		  
	    
	    for (i=1; i<=lastRow; i++) {
	      	 var aRow = document.getElementById('component_percentage' + i);
		   
			 rowVal = aRow.value;
			 total=total+Math.abs(rowVal);

			 if(total > 100){
					alert('You have exceeded total percentage of 100% ');					
					aRow.value=0;
					aRow.focus();
					return;
			}	
	    }  
}


function validateRow()
{	
	    var tbl = document.getElementById('tblComponent');	    
	    var lastRow = tbl.rows.length - 3;
	  
	    var i;
	    var total=0;		  
	    
	    for (i=1; i<=lastRow; i++) {
	      	  var aRow = document.getElementById('component_percentage' + i);
		   
		      if (aRow.value.length <= 0) {
		        alert('Row ' + i + ' is empty');
		        return false;
		      }

	         //get total percentage
			 rowVal = aRow.value;
			 total=total+Math.abs(rowVal);	
	    }  
	    
	    if(lastRow==0){
	    	alert('There is no assessment component entered.');
			return false;
	    }
	
		if(total !=100){
			alert('Please make sure the total percentage is 100%');
			return false;
		}
		
		
					    
 	return true;
}

function save(){
	$returnVal = validateRow(document.form1);

	if($returnVal==true){	   
		document.form1.submit();
	}
}

function back(){
	window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'index'), 'default', true);?>";
}


</script>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
		
			<li>
				<a href="#" onClick="save()">
				<span class='save'></span>Save</a>
			</li>
			
			<li>
				 <a  href="#" onclick="addRowToTable();">
					<span class='add'></span>
					Add Row
				 </a>
			</li>
			<li>
				<a href="#" onClick="removeRowFromTable();">
					<span class='remove' align="center"></span>
					Remove Row
				</a>
			</li>
			
			<li>							
					<a href="#" onClick="back()">
						<span class='back'></span>Back</a>				
			</li>	
			
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br>
<div style="width:100%;">


<table class="table" width="600px" cellpadding="5" cellspacing="1" border="0">
	<tr>
		    <th width="20%"><?php echo $this->translate("Programme Name"); ?></th>   
		    <td><?php echo $this->program['ArabicName'];?></td>   
	</tr>
	<tr>
		    <th width="20%"><?php echo $this->translate("Branch Name"); ?></th>   
		    <td><?php echo $this->branch['BranchName'];?></td>   
	</tr>
	<tr>
		    <th width="20%"><?php echo $this->translate("Semester Name "); ?></th>   
		    <td><?php echo $this->semester[0]['SemesterMainName'];?></td>   
	</tr>
	<tr>
		    <th><?php echo $this->translate("Subject Name "); ?></th>   
		    <td><?php echo $this->subject['BahasaIndonesia'];?> (<?php echo $this->subject['SubCode'];?>)</td>   
	</tr>
</table>
<br>

<span id="tbltype1" >

<br>
<h2>Add Assessment Component Instruction</h2>
<ul style="1">
	<li>To add more than one(01) component, click on "Add Row" button.</li>
	<li>To remove row, click on "Remove Row" button.</li>
	<li>Fill in the information required then click "Save" button to save.</li>
</ul>
<br>

<form name="form1" action="" method="post">
<table id="tblComponent" class="table" width="80%" cellpadding="5" cellspacing="1" >
  <tr>
    <th colspan="8">Assessment Component List.</th>
  </tr>
  <tr>
    <td width="5px"><?php echo $this->translate("No");?></td>   
    <td><?php echo $this->translate("Main Component Name");?></td>
    <td><?php echo $this->translate("Total Mark");?></td>  
    <td><?php echo $this->translate("Percentage");?></td>
    <td><?php echo $this->translate("Minimum Mark");?></td>
    <td><?php echo $this->translate("Allow Appeal");?></td>
    <td><?php echo $this->translate("Allow Resit");?></td> 
    <td><?php echo $this->translate("Allow Null");?></td> 
  </tr>
  <tr>
  <?php $no=1;?>
    <td><input type="text" name="ordercomponent<?php echo $no;?>" id="ordercomponent<?php echo $no;?>" size="5" value="<?php echo $no;?>"></td>   
		  </td>  
    <td>  
    <select name="component_id1" id="component_id1">
    		<option value="0">-- <?php echo $this->translate("Please Select")?> --</option>
        <?php foreach ($this->components as $component){?>
    		<option value="<?php echo $component["key"]?>"><?php echo $component["value"]?></option>
    	<?php } 
		
		?>
    </select>
    </td>
    <td><input type="text" name="component_total_mark1" id="component_total_mark1" onblur="onGetTotalMark();"></input></td>  
    <td><input type="text" name="component_percentage1" id="component_percentage1" onblur="onGetTotalPercentage();"></input></td>
    <td><input type="text" name="min_mark<?php echo $no;?>" id="min_mark<?php echo $no;?>"  size=6 value="<?php //echo $component["min_mark"]?>"></input></td>
      <td><input type="checkbox" name="appeal<?php echo $no;?>" id="appeal<?php echo $no;?>" value="1"></td>
		    <td><input type="checkbox" name="resit<?php echo $no;?>" id="resit<?php echo $no;?>" value="1"></td>
		     <td><input type="checkbox" name="allownull<?php echo $no;?>" id="allownull<?php echo $no;?>" value="1"></td>
  </tr>
  <tr>
    <td width="5px">&nbsp;</td>
    <td><?php echo $this->translate("Total Mark");?></td>  
    <td><input type="text" name="total_mark" id="total_mark"  value="" readonly></td> 
    <td><input type="hidden" name="total_percentage" id="total_percentage"  value="100" readonly>100%</td>
     
  </tr>
</table>

<input type="hidden" name="iteration" id="iteration" value="1"></input>
<input type="hidden" name="idSemester" id="idSemester" value="<?php echo $this->idSemester;?>"></input>
<input type="hidden" name="idProgram" id="idProgram" value="<?php echo $this->idProgram;?>"></input>
<input type="hidden" name="idBranch" id="idBranch" value="<?php echo $this->idBranch;?>"></input>

<input type="hidden" name="idSubject" id="idSubject" value="<?php echo $this->idSubject;?>"></input>
</form>


</span>

</div>