<script type="text/javascript">


function addRowToTable()
{

  var tbl = document.getElementById('tblComponent');
  var lastRow = tbl.rows.length; 

  // if there's no header row in the table, then iteration = lastRow + 1
  var iteration = lastRow-2;
  var row = tbl.insertRow(lastRow-1);

  document.getElementById('iteration').value = iteration

  // left cell
  var cellLeft = row.insertCell(0);
  var textNode = document.createTextNode(iteration);
  cellLeft.appendChild(textNode);  

  // left cell
  var cellLeft = row.insertCell(1);
  var textNode1 = document.createTextNode('');
  cellLeft.appendChild(textNode1);

  
  // select cell component name
  var component_id = row.insertCell(2);
  var ci = document.createElement('select');
  ci.name = 'component_id' + iteration;
  ci.options[0] = new Option('-- Sila Pilih --', '0');
     
  <? $i=1; foreach ($this->components as $component){ ?> 
  ci.options[<?php echo $i;?>] = new Option('<?php echo $component["value"]?>', '<?php echo $component["key"]?>');
  <? $i++; } ?>

  component_id.appendChild(ci);
  


  //component_total_mark
  var component_total_mark = row.insertCell(3);
  var ctm = document.createElement('input');
  ctm.type = 'text';
  ctm.name = 'component_total_mark' + iteration;
  ctm.id = 'component_total_mark'+ iteration;
  ctm.size = 20;
  
 // ctm.onkeypress = keyPressTest;
  ctm.onblur = onGetTotalMark;  
  component_total_mark.appendChild(ctm);



  //component_percentage
  var component_percentage = row.insertCell(4);
  var cw = document.createElement('input');
  cw.type = 'text';
  cw.name = 'component_percentage' + iteration ;
  cw.id = 'component_percentage'+ iteration;
  cw.size = 20;

  cw.onblur = onGetTotalPercentage;  
  component_percentage.appendChild(cw);

  
  
}

function keyPressTest(e, obj)
{
  var validateChkb = document.getElementById('chkValidateOnKeyPress');
  if (validateChkb.checked) {
    var displayObj = document.getElementById('spanOutput');
    var key;
    if(window.event) {
      key = window.event.keyCode; 
    }
    else if(e.which) {
      key = e.which;
    }
    var objId;
    if (obj != null) {
      objId = obj.id;
    } else {
      objId = this.id;
    }
    displayObj.innerHTML = objId + ' : ' + String.fromCharCode(key);
  }
}


function removeRowFromTable(total)
{
	
  var curval=3;
  newtotal=Math.abs(total)+Math.abs(curval);
  
  var tbl = document.getElementById('tblComponent');
  var lastRow = tbl.rows.length;
 
  
  curval = document.getElementById('iteration').value;
  if (lastRow > newtotal) {
	  tbl.deleteRow(lastRow - 2);  
      document.getElementById('iteration').value = curval-1;
  }else{
      alert('Sorry you cannot remove this component. Click on checkbox then click delete button to delete.');
  }
}

function onGetTotalMark(){

	 var tbl = document.getElementById('tblComponent');
	 var lastRow = tbl.rows.length - 3;

	 var main_component_total_mark = $("#total_mark").val();
	 
	 var i;
	 var total=0;		  
	    
	 for (i=1; i<=lastRow; i++) {
		 
    	 var aRow = document.getElementById('component_total_mark' + i);
    	 
		 rowVal = aRow.value;
		 total=total+Math.abs(rowVal);

		 if(total > main_component_total_mark){
				alert('You have exceeded Total Mark of '+ main_component_total_mark);					
				aRow.value=0;
				aRow.focus();
				return;
		}
  	}  
	 	         
}


function onGetTotalPercentage(){

    	//get total percentage
	    var tbl = document.getElementById('tblComponent');
	    var lastRow = tbl.rows.length - 3;
	  
	    var i;
	    var total=0;		  
	    
	    for (i=1; i<=lastRow; i++) {
	      	 var aRow = document.getElementById('component_percentage' + i);
		   
			 rowVal = aRow.value;
			 total=total+Math.abs(rowVal);

			 if(total > 100){
					alert('You have exceeded total percentage of 100% ');					
					aRow.value=0;
					aRow.focus();
					return;
			}	
	    }  
}


function validateRow()
{	
	    var tbl = document.getElementById('tblComponent');	    
	    var lastRow = tbl.rows.length - 3;
	  
	    var i;
	    var total=0;		  
	    
	    for (i=1; i<=lastRow; i++) {
	      	  var aRow = document.getElementById('component_percentage' + i);
		   
		      if (aRow.value.length <= 0) {
		        alert('Row ' + i + ' is empty');
		        return false;
		      }

	         //get total percentage
			 rowVal = aRow.value;
			 total=total+Math.abs(rowVal);	
	    }  
	    
	    if(lastRow==0){
	    	alert('There is no assessment component entered.');
			return false;
	    }
	
		if(total !=100){
			alert('Please make sure Total Percentage is 100%');
			return false;
		}
		
		
					    
 	return true;
}

function save(){
	$returnVal = validateRow(document.form1);

	if($returnVal==true){	   
		document.form1.submit();
	}
}

function back(){
	window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'view','idSemester'=>$this->idSemester,'idProgram'=>$this->idProgram,'idSubject'=>$this->idSubject), 'default', true);?>";
}

function deleteItem(){

	
	url="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'delete-item'),'default',true)?>";
	
    $('#form1').attr('action', url);
	$('#form1').submit();
	
}

</script>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onClick="save()">
				<span class='save'></span>Save</a>
			</li>
			<li>
				<a href="#" onClick="deleteItem();">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li>
				 <a  href="#" onclick="addRowToTable();">
					<span class='add'></span>
					Add Row
				 </a>
			</li>
			
			<li>
				<a href="#" onClick="removeRowFromTable('<?php echo count($this->component_item);?>');">
					<span class='remove' align="center"></span>
					Remove Row
				</a>
			</li>
			
			<li>							
					<a href="#" onClick="back()">
						<span class='back'></span>Back</a>				
			</li>	
			
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br>
<div style="width:100%;">


<table class="table" width="00px" cellpadding="5" cellspacing="1" border="0">
	<tr>
		    <th width="25%"><?php echo $this->translate("Programme Name"); ?></th>   
		    <td><?php echo $this->program['ArabicName'];?></td>   
	</tr>
	<tr>
		    <th width="25%"><?php echo $this->translate("Semester Name "); ?></th>   
		    <td><?php echo $this->semester[0]['SemesterMainName'];?></td>   
	</tr>
	<tr>
		    <th><?php echo $this->translate("Subject Name "); ?></th>   
		    <td><?php echo $this->subject['BahasaIndonesia'];?> (<?php echo $this->subject['SubCode'];?>)</td>   
	</tr>
	<tr>
		    <th><?php echo $this->translate("Main Component Name "); ?></th>   
		    <td><?php echo $this->main_component['component_name'];?></td>   
	</tr>
</table>
<br>

<span id="tbltype1" >

<br>
<h2>Add Assessment Component Instruction</h2>
<ul style="1">
	<li>To add more than one(01) component, click on "Add Row" button.</li>
	<li>To remove row, click on "Remove Row" button.</li>
	<li>Fill in the information required then click "Save" button to save.</li>
</ul>
<br>

<form name="form1" id="form1" action="" method="post">
<table id="tblComponent" class="table" width="80%" cellpadding="5" cellspacing="1" >
  <tr>
    <th colspan="5">Assessment Component List.</th>
  </tr>
  <tr>
    <td width="5px"><?php echo $this->translate("No");?></td>   
    <td width="5px" align="center"></td>   
    <td><?php echo $this->translate("Item Component Name");?></td>
    <td><?php echo $this->translate("Total Mark");?></td>  
    <td><?php echo $this->translate("Percentage");?></td>
     
  </tr>
   <?php 
		  $no=1;		
		  foreach ($this->component_item as $component){?>
		     
		  <tr>
		    <td>&nbsp;<?php echo $no;?>.</td>   
		    <td>	
		    <input type="hidden" name="IdMarksDistributionDetails<?php echo $no;?>" id="IdMarksDistributionDetails<?php echo $no;?>" value="<?php echo $component["IdMarksDistributionDetails"]?>">	    
		    <input type="checkbox" name="id[]" id="id[]" value="<?php echo $component["IdMarksDistributionDetails"]?>"></input></td>		    
		    <td>		
		     <input type="hidden" name="component_id<?php echo $no;?>" value="<?php echo $component["IdComponentItem"]?>">   
		     <input type="text" name="component_name<?php echo $no;?>" value="<?php echo $component["component_name"]?>" readonly>		    
		    </td>
		     <td><input type="text" name="component_total_mark<?php echo $no;?>" id="component_total_mark<?php echo $no;?>" value="<?php echo $component["Weightage"]?>" onblur="onGetTotalMark();"></input></td>		    
		   
		    <td><input type="text" name="component_percentage<?php echo $no;?>" id="component_percentage<?php echo $no;?>" value="<?php echo $component["Percentage"]?>"  onblur="onGetTotalPercentage('<?php echo count($this->component_item);?>');"></input></td>
		    
		   
		   </tr>
		  <?php $no++; } ?><!--
 
 
  <tr>
    <td>1</td>  
    <td>  
    <select name="component_id1" id="component_id1">
    		<option value="0">-- <?php echo $this->translate("Please Select")?> --</option>
        <? foreach ($this->components as $component){?>
    		<option value="<?php echo $component["key"]?>"><?php echo $component["value"]?></option>
    	<? } ?>
    </select>
    </td>
    <td><input type="text" name="component_total_mark1" id="component_total_mark1" onblur="onGetTotalMark();"></input></td>  
    <td><input type="text" name="component_percentage1" id="component_percentage1" onblur="onGetTotalPercentage();"></input></td>
      
  </tr>
  -->
  
  <tr>
    <td width="5px">&nbsp;</td>
    <td width="5px">&nbsp;</td>
    <td><?php echo $this->translate("Total Mark");?></td>  
    <td><input type="text" name="total_mark" id="total_mark"  value="<?php echo $this->main_component["TotalMark"]; ?>" readonly></td> 
    <td><input type="hidden" name="total_percentage" id="total_percentage"  value="100" readonly>100%</td>
     
  </tr>
</table>

<input type="hidden" name="iteration" id="iteration" value="<?php echo count($this->component_item); ?>"></input>
<input type="hidden" name="IdMarksDistributionMaster" id="IdMarksDistributionMaster" value="<?php echo $this->IdMarksDistributionMaster;?>"></input>
<input type="hidden" name="idSemester" id="idSemester" value="<?php echo $this->idSemester;?>"></input>
<input type="hidden" name="idProgram" id="idProgram" value="<?php echo $this->idProgram;?>"></input>
<input type="hidden" name="idSubject" id="idSubject" value="<?php echo $this->idSubject;?>"></input>
</form>


</span>

</div>