<script>
function add(){	
	window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'add','idSemester'=>$this->idSemester,'idProgram'=>$this->idProgram,'idBranch'=>$this->idBranch,'idSubject'=>$this->idSubject),'default',true);?>";
}

function edit(){	
	window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'edit','idSemester'=>$this->idSemester,'idProgram'=>$this->idProgram,'idBranch'=>$this->idBranch,'idSubject'=>$this->idSubject),'default',true)?>";
}

function Operator(){	
	window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'operator','idSemester'=>$this->idSemester,'idProgram'=>$this->idProgram,'idBranch'=>$this->idBranch,'idSubject'=>$this->idSubject),'default',true)?>";
}

function back(){
	window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'index'), 'default', true);?>";
}

</script>



<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<?php if($this->total > 0){?>
			<li>
				<a href="#" onClick="Operator()">
				<span class='edit'></span>Operator</a>
			</li>
			<?php } ?>
		  	<?php if($this->total > 0){?>
			<li>
				<a href="#" onClick="edit()">
				<span class='edit'></span>Edit</a>
			</li>
			<?php }else{ ?>
			<li>
				<a href="#" onClick="add()">
				<span class='add'></span>Add</a>
			</li>
			<?php } //end if?>
			<li>							
					<a href="#" onClick="back()">
						<span class='back'></span>Back</a>				
			</li>	
			
			
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br>
<div style="width:100%;">

<table class="table" width="600px" cellpadding="5" cellspacing="1" border="0">
	<tr>
		    <th width="20%"><?php echo $this->translate("Programme Name"); ?></th>   
		    <td><?php echo $this->program['ArabicName'];?></td>   
	</tr>
	<tr>
		    <th width="20%"><?php echo $this->translate("Branch Name"); ?></th>   
		    <td><?php echo $this->branch['BranchName'];?></td>   
	</tr>
	<tr>
		    <th width="20%"><?php echo $this->translate("Semester Name "); ?></th>   
		    <td><?php echo $this->semester[0]['SemesterMainName'];?></td>   
	</tr>
	<tr>
		    <th><?php echo $this->translate("Subject Name "); ?></th>   
		    <td><?php echo $this->subject['BahasaIndonesia'];?> (<?php echo $this->subject['SubCode'];?>)</td>   
	</tr>
</table>
<br>
<br><br>	
	
	<table  class="table" width="100%" cellpadding="5" cellspacing="1" >
		  <tr>
		    <th colspan="8">Assessment Component List.</th>
		  </tr>
		  <tr>
		    <th>No</th>   
		    <th>Component Name</th>
		    <th>Component Item</th>
		    <th width="10%">Item Mark</th>  
		    <th width="10%">Total Mark</th>
		    <th width="10%">Item Percentage</th>
		    <th width="10%">Total Percentage</th>	
		    <th width="15%">Action</th>
		  </tr>
		  <?php 
		  if($this->rs_component){		
		  $no=1;
		  foreach ($this->rs_component as $component){
		  ?>
		   <tr>
		    <td>&nbsp;<?php echo $component["OrderComponent"];?>.</td>   
		    <td>&nbsp;<?php echo $component["component_name"]?></td>
		    <td>&nbsp;</td>   
		    <td>&nbsp;</td> 
		    <td align="center">&nbsp;<?php echo $component["Marks"];?></td>
		    <td align="center">&nbsp;</td>
		    <td align="center">&nbsp;<?php echo $component["Percentage"];?></td>		
		     <td align="center">		       
		        <a class="editLink" href="<?php echo $this->url(array('module'=>'examination','controller'=>'mark-distribution','action'=>'edit-item','idSemester'=>$this->idSemester,'idProgram'=>$this->idProgram,'idSubject'=>$this->idSubject,'id'=>$component["IdMarksDistributionMaster"]),'default',true)?>" >Add/Manage Item</a>&nbsp;		    	
			</td>   
		   </tr>
		   
		    <?php 
		       //get component item 
		  	   $oCompitem = new Examination_Model_DbTable_Marksdistributiondetails();	
		  	   $component_item = $oCompitem->getListComponentItem($component["IdMarksDistributionMaster"]);
		  	   if($component_item){
		  	   	foreach ($component_item as $item){
		   ?>
			    <tr bgcolor="#FFFFF0">
				    <td>&nbsp;</td>   
				    <td>&nbsp;</td>
				    <td>&nbsp;<?php echo $item["ComponentName"]?></td>				    
				    <td align="center">&nbsp;<?php echo $item["Weightage"]?></td>
				    <td align="center">&nbsp;</td> 
				    <td align="center">&nbsp;<?php echo $item["Percentage"]?></td>
				    <td align="center">&nbsp;</td>
				    <td>&nbsp;</td> 				     
			    </tr>
		   <?php }   
				}//end if item?>
		   
		  <?php $no++; }
	}else{ ?>
	<tr bgcolor="#FFFFFF">
				    <td colspan="8"><font color="red"></>No assessment component has been setup.</font></td>   
			    </tr>
	<?php }
	?>
  </table>
</div>