<style>
body {
	background-image: url('/images/images/index/vector2.jpg');
}
.ade {
  background-color: #ffffff;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
}
.topnav {
  overflow: hidden;
  background-color: #7A7346;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #AB9F5A;
  color: black;
}

.topnav a.active {
  background-color: #C8B858;
  color: white;
}

.topnav-right {
  float: right;
}

input[type="submit"] {
  background-color: #575445;
  color: black;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
	width: 90px; 
    padding: 20px; 
    cursor: 
    pointer; 
    box-shadow: 6px 6px 5px; #999; 
    -webkit-box-shadow: 6px 6px 5px #575445; 
    -moz-box-shadow: 6px 6px 5px #999; 
    font-weight: bold; 
    background: #B4A768; 
    color: #000; 
    border-radius: 10px; 
    border: 1px solid #999; 
    font-size: 100%;
}
</style>
</head>
<body>

<!DOCTYPE html>
<html>
<head>
<style>
html, body {
  height: 100%;
}



img.two {
  height: 40%;
  width: 100%;
}

}
</style>
</head>
</html>

<div class="topnav">
  <a  href="/homepage/homepage/view">Home</a>
  <a href="#referensi">Referensi</a>
   <a href="#Kurikulum" class="active">Kurikulum</a>
  <a href="#penjadwalan">Penjadwalan</a>
  <a href="#krs">KRS</a>
  <a href="#transcript">Transcript</a>
  <div class="topnav-right">
    <a href="/index">Logout</a>
    
  </div>
</div>
</style>

<form name = "datamhsform" method="post"><br>
<div class="ade">
<fieldset><legend> <?php echo "Data Entry Kurikulum Universitas Trisakti"?></legend>
<input type = "hidden" id= "id" name="id" value="<?php echo $this->kurikuluma['id']?>">
<table>
<tr><th>SEMESTER</th>
<td><input type="text" name="semester" id= "semester" value="<?php echo $this->kurikuluma['semester']?>">
<tr><th>KODE MK</th>
<td><input type="text" name="kodemk" value="<?php echo $this->kurikuluma['kodemk']?>">
<tr><th>MATA KULIAH</th>
<td><input type="text" name="mata_kuliah" value="<?php echo $this->kurikuluma['matakuliah']?>">
<tr><th>PRASYARAT MATA KULIAH</th>
<td><textarea rows="5" cols="50"name = "tentang_mk" id="tentang_mk"><?php echo $this->kurikuluma['tentang_mk']?></textarea>
<br><tr><th>BOBOT</th>
<td><input type="text" name="bobot" value="<?php echo $this->kurikuluma['sks']?>">
<br><tr><th>DOSEN</th>
<td><input type="text" name="dosen" value="<?php echo $this->kurikuluma['dosen']?>">
<br><br>
<tr><td colspan="2">

<input type="submit" name = "save" value="save">&nbsp;&nbsp;&nbsp;
<input type="submit" name = "delete" value="delete">&nbsp;&nbsp;&nbsp;
<input type="submit" name = "update" value="update">&nbsp;&nbsp;&nbsp;
<input type="submit" name = "search" value="search">&nbsp;&nbsp;&nbsp;
</td></tr>
</table>
</form><br><br>
<mark><b>NB: Search berdasarkan kode mata kuliah.</b></mark>
</fieldset>
</div>
<br>

<div class="ade">
<fieldset><legend>Data Kurikulum Sistem Informasi Universitas Trisakti</legend>
<br>
<table class="table" border="1" style="margin: auto;"><tr><th>SEMESTER</th><th>KODE MK</th><th>MATA KULIAH</th><th>TENTANG MATA KULIAH</th><th>BOBOT</th><th>DOSEN</th></tr>
<?php foreach($this->kurmhs as $kura) {?> 
		<Tr><td align="center"><?php echo $kura['semester'];?></td> 
		<td align="center"><?php echo $kura['kodemk'];?></td> 
		<td align="center"><?php echo $kura['matakuliah'];?></td> 
		<td align="center"><?php echo $kura['tentang_mk'];?></td> 
		<td align="center"><?php echo $kura['sks'];?></td> 
		<td align="center"><?php echo $kura['dosen'];?></td></Tr> 
		<?php }?> 
		</table> <br>

</div>
</fieldset>
<br>

		