<script>

function back(){
	window.location="<?php echo $this->url(array('module'=>'examination','controller'=>'answer-schema','action'=>'detail','idSemester'=>$this->idSemester,'idProgram'=>$this->idProgram,'idSubject'=>$this->idSubject,'idMaster'=>$this->IdMarksDistributionMaster,'idDetail'=>$this->IdMarksDistributionDetails), 'default', true);?>";
}

</script>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>							
					<a href="#" onClick="back()">
					<span class='back'></span>Back</a>				
			</li>
		</ul>
	</div>
</div>
<br>

<fieldset>
	<table class="table" width="600px" cellpadding="5" cellspacing="1" border="0">
	<tr>
		    <th width="20%"><?php echo $this->translate("Programme Name"); ?></th>   
		    <td><?php echo $this->program['ArabicName'];?></td>   
	</tr>
	<tr>
		    <th width="20%"><?php echo $this->translate("Semester Name "); ?></th>   
		    <td><?php echo $this->semester[0]['SemesterMainName'];?></td>   
	</tr>
	<tr>
		    <th><?php echo $this->translate("Subject Name "); ?></th>   
		    <td><?php echo $this->subject['BahasaIndonesia'];?> (<?php echo $this->subject['SubCode'];?>)</td>   
	</tr>
	<tr>
			<th width="150px"><?php echo $this->translate("Component Name"); ?></th>
			<td>
			  <?php 
			  echo $this->main_component["component_name"]; 
			  
			  if($this->component_item){
			  echo ' - '.$this->component_item["ComponentName"];
			  }
			  ?>
			</td>				
			
	</tr>
	
</table>
</fieldset>

<br />
<div style="width:100%;">
<?php 
	//echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="300px" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th width="100px"><?php echo $this->translate("Question Number"); ?></th>
		<th><?php echo $this->translate("Answer"); ?></th>
	</tr>
	
	<?php
	if($this->schemaDetail){ 
		$i=0;
		foreach ($this->schemaDetail as $data): 
		?>
		<tr <?php echo $i%2==0?"class='shade'":""; ?>>
			<td align="center"><?php echo $data['sad_ques_no']; ?></td>
			<td align="center"><?php echo $data['sad_ques_ans']; ?></td>
		</tr>
		<?php 
		$i++;
		endforeach;
	}else{
		?>
		<tr>
			<td colspan="3" align="center">
				<?php echo $this->translate("No Data Available"); ?>
			</td>
		</tr>
		<?php 
	}
	?>

</table>
</div>
<?php 
	//echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>








