<style>
body {
 background-image: url('/images/images/index/trisaktilogo.png');
		background-repeat: no-repeat;
		background-position:right;
 	    background-size: 500px 500px;
  		background-attachment: fixed;
}
.krs {
  background-color: #d7d7c1;
  width: 900px;
  margin: auto;
  padding: 30px;
  opacity: 0.95;
  font-size: 16px;
}

.topnav {
  overflow: hidden;
  background-color: #7A7346;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #AB9F5A;
  color: black;
}

.topnav a.active {
  background-color: #C8B858;
  color: white;
}

.topnav-right {
  float: right;
}

input[type="submit"] {
  background-color: #575445;
  color: black;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
 width: 90px; 
    padding: 20px; 
    cursor: 
    pointer; 
    box-shadow: 6px 6px 5px; #999; 
    -webkit-box-shadow: 6px 6px 5px #575445; 
    -moz-box-shadow: 6px 6px 5px #999; 
    font-weight: bold; 
    background: #B4A768; 
    color: #000; 
    border-radius: 10px; 
    border: 1px solid #999; 
    font-size: 100%;
}
</style>
</head>
<body>

<!DOCTYPE html>
<html>
<head>
<style>
html, body {
  height: 100%;
}



img.two {
  height: 40%;
  width: 100%;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: #C8B858;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: #C8B858;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #C2AF4D;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}


 #tfheader{
  background-color:#c3dfef;
 }
 #tfnewsearch{
  float:right;
  padding:1px;
 }
 .tftextinput{
  margin: 0;
  padding: 5px 10px;
  font-family: Arial, Helvetica, sans-serif;
  font-size:14px;
  border:1px solid #0076a3; border-right:0px;
  border-top-left-radius: 5px 5px;
  border-top-right-radius: 5px 5px;
  border-bottom-left-radius: 5px 5px;
  border-bottom-right-radius: 5px 5px;
 }
 .tfbutton {
  margin: 0;
  padding: 10px 60px;
  font-family: Arial, Helvetica, sans-serif;
  font-size:14px;
  outline: none;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  color: #ffffff;
  border: solid 1px #0076a3; border-right:0px;
  background: #0095cd;
  background: -webkit-gradient(linear, left top, left bottom, from(#00adee), to(#0078a5));
  background: -moz-linear-gradient(top,  #00adee,  #0078a5);
  border-top-right-radius: 5px 5px;
  border-bottom-right-radius: 5px 5px;
 }
 .tfbutton:hover {
  text-decoration: none;
  background: #007ead;
  background: -webkit-gradient(linear, left top, left bottom, from(#0095cc), to(#00678e));
  background: -moz-linear-gradient(top,  #0095cc,  #00678e);
 }
 /* Fixes submit button height problem in Firefox */
 .tfbutton::-moz-focus-inner {
   border: 0;
 }
 .tfclear{
  clear:both;
 }

</style>
</head>
</html>

<div class="topnav">
  <a  href="/homepage/homepage/view">Home</a>
  <a href="#referensi">Referensi</a>
  <div class="dropdown" class="active">
    <button class="dropbtn">Kurikulum
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">View Kurikulum</a>
      <a href="/kurikulum/kurikulum/view">Edit Kurikulum</a>
    </div>
  </div> 
  <a href="#penjadwalan">Penjadwalan</a>
  <a href="#krs">KRS</a>
  <a href="#transcript">Transcript</a>
  <div class="topnav-right">
    <a href="/index">Logout</a>
    
  </div>
</div>
</style>

<form name = "datamhsform" method="post"><br>
<div class="krs">
<fieldset>
<p>Berikut tombol pencarian untuk mencari data berdasarkan semester:</p>
  <form id="tfnewsearch" method="get" action="http://www.google.com">
  <input style="" type="text" class="tftextinput" name="q" size="21" maxlength="120">&nbsp;&nbsp;<input type="submit" value="search" class="tfbutton">
  </form>
</fieldset>
</div>
<br>




<br><div class="krs">
<fieldset><legend>Data Kurikulum Sistem Informasi Universitas Trisakti</legend>
<br>
<table class="table" border="1" style="margin: auto;"><tr><th>SEMESTER</th><th>KODE MK</th><th>MATA KULIAH</th><th>TENTANG MATA KULIAH</th><th>BOBOT</th><th>DOSEN</th></tr>
<?php foreach($this->kurmhs as $kura) {?> 
  <Tr><td align="center"><?php echo $kura['semester'];?></td> 
  <td align="center"><?php echo $kura['kodemk'];?></td> 
  <td align="center"><?php echo $kura['mata_kuliah'];?></td> 
  <td align="center"><?php echo $kura['tentang_mk'];?></td> 
  <td align="center"><?php echo $kura['bobot'];?></td> 
  <td align="center"><?php echo $kura['dosen'];?></td></Tr> 
  <?php }?> 
  </table> <br>

</div>
</fieldset>
<br>