<head>
<script language='javascript'
	src='<?php echo $this->baseUrl(); ?>/js/jquery-1.4.3.js'></script>
<script type="text/javascript">
    dojo.addOnLoad(function (){

    });

    function fnToggleTabs(TabAction,CurrentTabId,NextTabId){
      if(TabAction == "Next"){
        var flag = Validateform(CurrentTabId);
        if(flag){
          var mainTabContainerId = dijit.byId("mainTabContainer")
          var tabContainerId = dijit.byId(NextTabId);
          mainTabContainerId.selectChild(tabContainerId);
        }
      }else if(TabAction == "Back"){
        var mainTabContainerId = dijit.byId("mainTabContainer")
        var tabContainerId = dijit.byId(NextTabId);
        mainTabContainerId.selectChild(tabContainerId);
      }
    }


  </script>
<style type="text/css">
div.cabinet {
	width: 300px;
	background: url(<?php echo $this->baseUrl(); ?>/
	images /button.gif) 0 0 no-repeat;
	/*height: 100px;*/
	display: block;
	cursor: pointer;
}

div.cabinet div.MultiFile-wrap div.MultiFile-list {
	height: 70px;
	width: 600px;
	display: block;
	overflow: auto;
}

div.cabinet div.MultiFile-wrap div.MultiFile-list div.MultiFile-label a.MultiFile-remove
	{
	background: url(<?php echo $this->baseUrl();
	?>/
	images
	/delete.png)0
	0
	no-repeat;
}

div.cabinet input.file {
	position: relative;
	width: auto;
	opacity: 0;
	-moz-opacity: 0;
	filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0 );
}
</style>
</head>
<body class="claro">
	<fieldset>
		<legend>
			<?php echo $this->translate("Examination History"); ?>
		</legend>
		<table>
			<tr>
				<td>
					<div id="mainTabContainer" dojoType="dijit.layout.TabContainer"
						doLayout="false" tabPosition="top"
						style="width: 1100px; height: auto">
						<div dojoType="dijit.layout.ContentPane" id="tab-one"
							title="<?php echo $this->translate("Marks Distribution History"); ?>"
							style="height: auto; width: auto; overflow: auto">
							<?php echo $this->partial("examinationhistory/marksdistributionhistory.phtml", array('historyArray' => $this->historyArray));?>
						</div>
						<div dojoType="dijit.layout.ContentPane" id="tab-two"
							title="<?php echo $this->translate("Marks Entry History"); ?>"
							style="height: auto; width: auto; overflow: auto">
							<?php echo $this->partial("examinationhistory/marksentryhistory.phtml", array());?>
						</div>
					</div>
				</td>
			</tr>
		</table>
	</fieldset>
</body>
