<form name = "datamhsform" method="post">
<fieldset><legend> <?php echo "Data Entry Mahasiswa"?></legend>
<input type = "hidden" id= "id" name="id" value="<?php echo $this->datapersonal['id']?>_">
<table>
<tr><th>NIM</th>
<td><input type="text" name="nim" id= "nim" value="<?php echo $this->datapersonal['nim']?>">
<tr><th>NAMA</th>
<td><input type="text" name="nama" value="<?php echo $this->datapersonal['nama']?>">
<tr><th>ALAMAT</th>
<td><textarea rows="5" cols="50"name = "alamat" id="alamat"><?php echo $this->datapersonal['alamat']?></textarea>
<br><tr><th>NAMA PRODI</th>
<td><input type="text" name="prodi" value="<?php echo $this->datapersonal['prodi']?>">
<br><br>
<tr><td colspan="2">
<input type="submit" name = "save" value="save">
<input type="submit" name = "delete" value="delete">
<input type="submit" name = "update" value="update">
<input type="submit" name = "search" value="search">
<input type="submit" name = "approve" value="approve">
</td></tr>
</table>
</form>
</fieldset>

<table class="table"><tr><th>NIM</th><th>NAMA</th><th>ALAMAT</th><th>PRODI</th></tr>
<?php foreach($this->datamhs as $mhs) {?>
  <Tr><td><?php echo $mhs['nim'];?></td>
  <td><?php echo $mhs['nama'];?></td>
  <td><?php echo $mhs['alamat'];?></td>
  <td><?php echo $mhs['prodi'];?></td></Tr>
  <?php }?>
  </table>