<script type="text/javascript">
    dojo.addOnLoad(function(){
        <?php if (!$this->larrresult) { ?>
            dijit.byId('field5').set('value','');
            dijit.byId('field5').set('placeHolder','Select');
            dijit.byId('field8').set('value','');
            dijit.byId('field8').set('placeHolder','Select');
            dijit.byId('field20').set('value','');
            dijit.byId('field20').set('placeHolder','Select');
            dijit.byId('field10').set('value','');
            dijit.byId('field10').set('placeHolder','Select');
            dijit.byId('field27').set('value','');
            dijit.byId('field27').set('placeHolder','Select');
        <?php } ?>
    });
</script>
<fieldset>
	<legend>
		<?php echo $this->translate("Exam Resit Search"); ?>
	</legend>
	<form
		action="<?php echo $this->baseUrl(); ?>/examination/resitmarksappeal/index/search/1"
		method="POST">
		<table width="100%">
			<tr>
				<td><?php echo $this->translate('Student Id');?>
				</td>
				<td><?php echo $this->lobjform->field3;?></td>
				<td><?php echo $this->translate("Semester");?></td>
				<td><?php echo $this->lobjform->field8; ?></td>
			</tr>
			<tr>
				<td><?php echo $this->translate($this->Program);?></td>
				<td><?php echo $this->lobjform->field5; ?></td>
				<td><?php echo $this->translate("Course"); ?></td>
				<td><?php echo $this->lobjform->field27; ?></td>
			</tr>
			<tr>
				<td><?php echo $this->translate("Status");?></td>
				<td><?php echo $this->lobjform->field10; ?></td>
				<td><?php echo $this->translate("Mode");?></td>
				<td><?php echo $this->lobjform->field20; ?></td>
			</tr>
			<tr>
				<td><?php echo $this->translate("Application Id");?>
				</td>
				<td><?php echo $this->lobjform->field4; ?></td>
			</tr>
			<tr>
				<td colspan="6" style="height: 10px"></td>
			</tr>
			<tr>
				<td align="center" colspan="6"><?php echo $this->lobjform->Search; ?>
					<input type="button" class="NormalBtn" dojotype="dijit.form.Button"
					label="<?php echo $this->translate("Add"); ?>"
					onclick="window.location.href='<?php echo $this->url(array('module' => 'examination', 'controller' => 'resitmarksappeal', 'action' => 'addresitmarksappeal'), 'default', true); ?>';" />
					<?php echo $this->lobjform->Clear; ?>
				</td>
			</tr>
		</table>
	</form>
</fieldset>
</br>
<fieldset>
	<table class="table" width="100%" cellpadding="5" cellspacing="1">
		<tr>
			<th><?php echo $this->translate('Application Id'); ?>
			</th>
			<th><?php echo $this->translate("Student Id"); ?>
			</th>
			<th><?php echo $this->translate("Student Name"); ?>
			</th>
			<th><?php echo $this->translate("Program");?></th>
			<th><?php echo $this->translate("Component");?></th>
			<th><?php echo $this->translate("Status");?></th>
			<th><?php echo $this->translate("Mode");?></th>
		</tr>
		<?php if (count($this->paginator)): ?>
		<?php foreach ($this->paginator as $list): ?>
		<?php
		$url = $this->url(array('module' => 'examination', 'controller' => 'resitmarksappeal', 'action' => 'editresitmarksappeal', 'id' => $list['IdExaminationResitApplication']), 'default', true);
		?>
		<tr>
			<td><a href='<?php echo $url;?>'><?php echo $list['ExaminationResitApplicationCode']; ?>
			</a></td>
			<td><?php echo $list['StudentCode']; ?></td>
			<td><?php echo $list['StudentName']; ?></td>
			<td><?php echo $list['ProgramName'];?></td>
			<td><?php echo $list['componentname'];?></td>
			<td><?php echo $list['DefinitionDesc'];?></td>
			<td><?php echo $list['mode'];?></td>
		</tr>

		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</fieldset>
