<html>
<head>
 <title>MEMBUAT CETAK PRINT LAPORAN DENGAN PHP - WWW.MALASNGODING.COM</title>
</head>
<body>
 <fieldset><legend>Daftar Prestasi Akademik 
		<br>
						&nbsp;&nbsp;&nbsp;<em>Academic Transcript</em></legend>
		<br>
		Jurusan / Program Studi &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Teknik Informatika / Sistem Informasi  <br>
		<em>Department / Studi Program : Informatic Engineering / Information Sytem</em> <br>
		Konsentrasi &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Bersama <br>
		<em>Major In &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Common</em> <br>
		Program Pendidikan &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Sarjana | S1 <br>
		<em>Program &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: a 4-year undergraduate program</em>
		<br>
		<br>
		Nama &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <?php 'nama' ?>
		<br>
		Tempat/Tanggal Lahir  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <?php 'ttl '?>
		<br><br>
		<table border ="" width = "100%">

      <tr>
      		 <th>Nama Matakuliah</th>
             <th>Kode Matakuliah</th>
             <th>Jumlah SKS</th>
             <th>Ruangan</th>
             <th>Dosen</th>
             <th>Jadwal</th>
               
      </tr>
      <tr>
            
             
    </tr>
     <tr>
            
    </tr>
     <tr>
             
    </tr>
     <tr>
             
    </tr>
     <tr>
          
    </tr>
     <tr>
             
             
             
    </tr>
     <tr>
            
            
    </tr>
    </table>
</div>
</fieldset>
 <script>
  window.print();
 </script>
 
</body>
</html>