<script type="text/javascript">
dojo.addOnLoad(function(){
	var value = dijit.byId("SameLecturer").checked;
	 blockstafflist(value);
	
	});

function blockstafflist(value){

	if(value==true){
		dijit.byId('IdStaff').set('readOnly',true);
	}	
	else{
		dijit.byId('IdStaff').set('readOnly',false);
	}
}

</script>
<fieldset>
	<legend>
		<?php echo $this->translate("$this->Subject").' '.$this->translate("Staff").' '.$this->translate("Verification");?>
	</legend>
	<Form dojoType="dijit.form.Form" id="myForm"
		action="<?php echo $this->baseUrl();?>/examination/subjectstaffverification/subjectstaffverificationlist"
		method="post" name="myForm">
		<script type="dojo/method" event="onSubmit">
                if (this.validate()) {
					return true;
                } else {
                    return false;
                }
				</script>
		<table class="table" width="100%">
			<tr>
				<th colspan="4"><?php echo $this->translate("Marks").' '.$this->translate("Entry").' '.$this->translate("Setup");?>
				</th>
			</tr>
			<tr>
				<td><?php echo $this->translate($this->Subject).' '.$this->translate("Staff Verification");?><span>*</span></span>
				</td>
				<td><?php echo $this->subjectName;?></td>
				<td></td>
				<td></td>
				<?php echo $this->lobjSubjectstaffverificationForm->IdSubjectStaffVerification;?>
				<?php echo $this->lobjSubjectstaffverificationForm->UpdDate;?>
				<?php echo $this->lobjSubjectstaffverificationForm->UpdUser;?>
				<?php echo $this->lobjSubjectstaffverificationForm->IdSubject;?>
				</td>
			</tr>
			<tr>
				<td><?php echo $this->translate("Same Lecturer");?><span>*</span></td>
				<td><?php echo $this->lobjSubjectstaffverificationForm->SameLecturer;?>
				</td>
				<td><?php echo $this->translate("Select Staff");?><span>*</span></td>
				<td><?php echo $this->lobjSubjectstaffverificationForm->IdStaff;?></td>
			</tr>
			<tr>
				<td><?php echo $this->translate("Select Semester");?><span>*</span>
				</td>
				<td><?php echo $this->lobjSubjectstaffverificationForm->IdSemester;?>
				</td>
				<td><?php echo $this->translate("Active");?><span></span></td>
				<td><?php echo $this->lobjSubjectstaffverificationForm->Active;?></td>
			</tr>
			<tr>
				<td align="right" colspan="4"><?php echo $this->lobjSubjectstaffverificationForm->Save;?>
					<input type='button' class="NormalBtn" dojotype="dijit.form.Button"
					label="<?php echo $this->translate('Back')?>" value='click'
					onclick="window.location.href='<?php echo $this->url(array('module'=>'examination','controller'=>'subjectstaffverification', 'action'=>'index'),'default',true);?>';" />
				</td>
			</tr>
		</table>

	</Form>

</fieldset>
